// Aberturas alternativas dos eventos (mesma situação, outras palavras). O jogo sorteia entre a original e estas,
// com memória entre carreiras: a mesma abertura só volta depois das outras. Só eventos de texto fixo.
(function () {
  const D = window.CRAQUE_DATA;
  D.EV_INTRO = {
    renovar: ['A diretoria chamou para conversar: quer você por muitos anos.', 'O presidente quer evitar assédio de outros clubes e oferece um contrato longo.'],
    classico: ['A coxa ainda incomoda e o clássico é domingo. O técnico deixa a decisão com você.', 'Clássico no fim de semana, e você sente a coxa. O médico avisa, o técnico pergunta.'],
    festa: ['É aniversário do seu melhor amigo, na véspera do jogo. A festa promete.', 'O parça faz aniversário e a festa é hoje à noite. Amanhã tem jogo.'],
    sub20: ['A seleção sub-20 te chamou, mas o torneio bate com jogos importantes do clube.', 'Convocação para a sub-20! Só que o clube vai jogar partidas decisivas no mesmo período.'],
    mentor: ['O veterano do elenco viu algo em você e ofereceu treinos extras depois do expediente.', 'O capitão chamou no canto: quer treinar com você todo dia depois do treino.'],
    patrocinio: ['Uma marca de material esportivo quer o seu rosto na próxima campanha.', 'O telefone tocou: uma grande marca esportiva quer você como garoto-propaganda.'],
    redes: ['Você provocou a torcida rival num vídeo, e ele explodiu nas redes.', 'Aquele vídeo zoando o rival viralizou. Todo mundo está comentando.'],
    joelho: ['O joelho deu sinal na pré-temporada. Os médicos pedem calma.', 'Um incômodo no joelho apareceu nos primeiros treinos. O departamento médico recomenda cautela.'],
    faltas: ['O preparador quer você uma semana inteira batendo faltas depois do treino.', 'Proposta do auxiliar: centenas de cobranças de falta por dia, durante uma semana.'],
    caridade: ['A escolinha onde você começou, na sua cidade, está para fechar. Pediram ajuda.', 'Uma escolinha de futebol da sua cidade natal corre o risco de fechar as portas e procura você.'],
    estudos: ['Falta terminar o ensino médio. A escola oferece aulas à noite, e o treino é às 7h.', 'A coordenação da escola liga: dá para concluir os estudos à noite, mas a rotina vai apertar.'],
    carro: ['Caiu o primeiro salário de verdade, e o vendedor da concessionária já sabe disso.', 'Primeiro salário alto na conta. O carrão dos sonhos está à venda logo ali.'],
    olheiro: ['Um olheiro de um gigante europeu está na arquibancada. Todos sabem por quem ele veio.', 'Avisaram no vestiário: tem olheiro de clube grande da Europa vendo o jogo hoje.'],
    empresario: ['O empresário mais famoso do país marcou um café com você.', 'O agente mais poderoso do futebol nacional quer cuidar dos seus contratos.'],
    dieta: ['A nova nutricionista cortou açúcar, fritura e refrigerante do cardápio.', 'Chegou uma nutricionista linha-dura no clube. Nada de doce, nada de fritura.'],
    fisgada: ['No aquecimento, a coxa fisgou. E o jogo de hoje é importante.', 'Uma fisgada na coxa durante o aquecimento. Faltam minutos para o jogo grande.'],
    jejum: ['São oito jogos sem marcar, e a imprensa já faz contagem regressiva.', 'Oito partidas sem gol. Os jornais já falam em seca.'],
    cobrador: ['Você e o camisa 10 querem ser o cobrador oficial de pênaltis.', 'Disputa no elenco: o camisa 10 quer os pênaltis, e você também.'],
    var: ['O VAR anulou seu gol no jogo grande por um ombro adiantado.', 'Impedimento de ombro: o VAR tirou o seu gol num jogo decisivo.'],
    provocacao: ['O zagueiro adversário passou o jogo te provocando e pisando no seu pé.', 'Provocação o jogo inteiro: o zagueiro rival não parou de pisar e falar no seu ouvido.'],
    volante: ['O técnico quer te testar mais adiantado, como volante que sai jogando.', 'Ideia do treinador: você de volante, para a saída de bola.'],
    reserva_gol: ['O goleiro reserva, de 19 anos, está pegando tudo nos treinos. A imprensa já pede ele.', 'O garoto de 19 anos que é seu reserva está voando, e os jornais notaram.'],
    goleiro_area: ['Acréscimos, perdendo por 1 a 0, escanteio. O banco grita para você ir para a área.', 'Último lance, 1 a 0 contra. Todo mundo pede para o goleiro subir.'],
    treino_gol: ['O novo preparador de goleiros trouxe um método europeu: reflexo, saída e jogo com os pés.', 'Preparador novo no clube, com ideias da Europa. Ele quer saber onde você quer evoluir.'],
    aereo: ['O auxiliar quer você no treino de cabeceio todo dia depois do treino normal.', 'Proposta da comissão: treino de bola aérea diário, depois do expediente.'],
    vestiario: ['Dois veteranos brigaram feio no vestiário depois da derrota. Todo mundo olhou para você.', 'Depois da derrota, dois jogadores experientes saíram no tapa. O grupo espera uma atitude sua.'],
    gringo: ['O técnico novo é estrangeiro, não fala o idioma do grupo e ainda desconfia de todos.', 'Chegou um treinador gringo. Ele não fala a língua do elenco e ainda não confia em ninguém.'],
    demitido: ['O técnico que apostou em você caiu depois de três derrotas seguidas.', 'Três derrotas e a diretoria demitiu o treinador que te deu chance.'],
    padrinho: ['Um garoto de 17 anos subiu da base e diz para todo mundo que você é o ídolo dele.', 'O menino de 17 anos que acabou de subir ao profissional pediu para treinar ao seu lado.'],
    casamento: ['Data marcada: o casamento vai ser na pré-temporada.', 'O casamento está chegando, bem na pré-temporada.'],
    filho: ['Seu filho deve nascer no dia do jogo decisivo.', 'A médica confirmou: o parto deve ser justo no dia da decisão.'],
    documentario: ['Uma plataforma de streaming quer filmar a sua temporada do começo ao fim.', 'Proposta de série documental: câmeras te acompanhando a temporada inteira.'],
    podcast: ['O maior podcast do país quer você por três horas no estúdio.', 'Convite para três horas de conversa no podcast mais ouvido do Brasil.'],
    negocio: ['Um amigo de infância quer você como sócio numa rede de academias.', 'Proposta de negócio: virar sócio de um amigo de infância numa rede de academias.'],
    reality: ['Um reality show quer você nas férias, com cachê alto e muita exposição.', 'Convite para um reality nas férias: dinheiro bom e câmeras o tempo todo.'],
    beneficente: ['Nas férias, um amigo organiza um jogo beneficente com ex-craques e artistas.', 'Jogo beneficente nas férias: ex-jogadores, cantores e humoristas em campo.'],
    amistosos: ['A seleção te chamou para dois amistosos no meio da temporada.', 'Convocação para dois amistosos da seleção, bem no meio do calendário do clube.'],
    adaptacao: ['Idioma novo, clima diferente e outro estilo de futebol. O começo está pesado.', 'A adaptação está difícil: a língua, o frio e o jeito de jogar são outros.'],
    manipulacao: ['Um desconhecido oferece dinheiro para você levar um amarelo num jogo específico.', 'Mensagem suspeita: pagam bem se você tomar um cartão amarelo num jogo marcado.'],
    lesionou: ['Numa dividida, você machucou feio um adversário. Foi sem querer, mas a imagem é forte.', 'A dividida foi dura e o adversário saiu de maca. Não foi intencional, mas as imagens chocaram.'],
    corte_salario: ['A diretoria quer renovar por mais um ano, mas pagando menos.', 'Proposta de renovação: mais uma temporada, só que com salário menor.'],
    curso_tecnico: ['Abriu turma do curso de treinador da federação, com aulas às segundas, seu dia de folga.', 'A federação oferece o curso de técnico às segundas-feiras, justo na folga.'],
    recuperacao: ['Um centro de recuperação famoso entre craques europeus oferece um programa para estender sua carreira.', 'Proposta de um centro de alto rendimento: tecnologia de ponta para você jogar mais anos.'],
    reserva_luxo: ['O técnico quer te poupar e usar a sua experiência saindo do banco.', 'Conversa franca com o treinador: ele prefere você entrando no segundo tempo.'],
    lateral: ['Os dois laterais se machucaram e o técnico pede que você quebre o galho.', 'Sem laterais disponíveis, o treinador quer você improvisado na posição.'],
    parceiro_zaga: ['O novo parceiro de zaga, de 20 anos, vem errando bastante.', 'Seu companheiro de zaga, de 20 anos, está numa fase de muitos erros.'],
    centroavante: ['O técnico quer saber: como você prefere jogar nesta temporada?', 'Conversa tática: o treinador deixa você escolher a sua função no ataque.'],
    analista_gol: ['O analista preparou um arquivo com os pênaltis de todos os batedores da liga.', 'Chegou um dossiê do analista: cada cobrança de pênalti dos batedores da liga.'],
    frango: ['Um chute fraco passou por baixo de você e virou meme.', 'Frango num chute sem perigo, e a internet não perdoou.'],
    bicho: ['O presidente promete bicho em dobro se o time vencer o clássico.', 'Prêmio dobrado prometido pela diretoria para quem vencer o clássico.'],
    pre_contrato: ['Seu contrato está acabando e outro clube oferece luvas para um pré-contrato.', 'Fim de contrato à vista. Um clube oferece luvas para você assinar desde já.'],
    receita: ['A Receita Federal está questionando seus contratos de imagem dos últimos anos.', 'Chegou uma notificação da Receita sobre seus contratos de imagem.'],
    apostas: ['Uma casa de apostas quer você na próxima campanha publicitária.', 'Proposta de patrocínio de uma casa de apostas, com cachê alto.'],
    emprestimo: ['Um amigo de infância pede dinheiro emprestado para salvar o negócio da família.', 'O telefone toca: um amigo antigo precisa de um empréstimo para não fechar o negócio da família.'],
    capa_game: ['O videogame de futebol mais vendido do mundo quer você na capa.', 'Convite para estampar a capa da nova edição do maior jogo de futebol do mundo.'],
    comemoracao: ['Os amigos insistem: está na hora de você ter uma comemoração só sua.', 'Todo craque tem uma comemoração marcante. Seus amigos acham que falta a sua.'],
    invasao: ['Um menino invadiu o campo no meio do jogo e correu para te abraçar.', 'No meio da partida, uma criança passa pelos seguranças e vem correndo na sua direção.'],
    critica: ['Um comentarista famoso disse na TV que você é "o jogador mais superestimado do país".', 'Ao vivo, na televisão, um comentarista te chamou de "o mais superestimado do país".'],
    musica: ['Um cantor famoso lançou uma música com o seu nome e quer você no clipe.', 'Saiu uma música com o seu nome, e o cantor convidou você para gravar o clipe.'],
    ofensas: ['Parte da torcida adversária passa o jogo te ofendendo de forma criminosa.', 'Ofensas criminosas da arquibancada adversária, jogo inteiro.'],
    torcida_tecnico: ['Três derrotas seguidas e a torcida grita contra o técnico. Os microfones vêm até você.', 'Depois da terceira derrota, o estádio pede a cabeça do técnico. Os repórteres querem a sua opinião.'],
    virose: ['Uma virose pegou metade do elenco na semana do jogo decisivo. Você acordou com febre.', 'Semana de decisão e uma virose derrubou o elenco. Você também está com febre.'],
    insonia: ['Jogos à noite, viagens e cabeça cheia: você não consegue dormir direito.', 'O sono sumiu. Entre viagens e jogos tarde da noite, você vira de um lado para o outro.'],
    pubalgia: ['A dor na virilha não passa. O médico apresenta duas opções.', 'Pubalgia: uma dor persistente na virilha, e duas formas de tratar.'],
    pai_empresario: ['Seu pai largou o emprego e quer ser o responsável pelos seus contratos.', 'Seu pai quer virar seu empresário. Ele já até pediu demissão.'],
    irmao: ['Seu irmão mais novo também sonha ser jogador e pede uma força.', 'Seu irmão caçula quer seguir os seus passos e pede ajuda.'],
    cachorro: ['Um vira-lata apareceu no CT e não sai do seu lado nos treinos.', 'Tem um cachorro de rua no CT que adotou você. Onde você vai, ele vai.'],
    concentracao: ['O novo técnico quer o elenco concentrado três dias antes de cada partida.', 'Regra nova: três dias de concentração antes de todo jogo.'],
    pretemporada: ['O clube marcou seis amistosos fora do país em duas semanas.', 'Excursão de pré-temporada: seis jogos no exterior em quinze dias.'],
    faixa: ['A temporada vai mal e parte do elenco acha que a braçadeira está pesando em você.', 'Fase ruim, e no vestiário já se comenta que a faixa de capitão está pesando.'],
    olimpiada: ['A convocação olímpica chegou. O clube não quer liberar, mas é a chance de uma medalha.', 'Você está na lista para as Olimpíadas. O clube resiste em te liberar.'],
    alojamento: ['O colega de quarto no alojamento ronca e joga videogame até as 3h. O treino é às 7h.', 'Videogame até de madrugada e ronco a noite toda: o colega de alojamento não deixa você dormir.'],
    vlog_base: ['Um amigo youtuber quer gravar a rotina da base: quarto, comida e treinos.', 'Proposta de um amigo que tem canal: uma série sobre a vida no alojamento.'],
    primeira_entrevista: ['Uma repórter te parou na saída do campo. É a sua primeira vez num microfone.', 'Microfone na sua frente pela primeira vez, ao vivo, na saída do gramado.'],
    ingressos: ['Trinta pessoas do bairro querem ingresso a cada jogo. O clube dá quatro.', 'O bairro inteiro quer ver você jogar, mas a sua cota é de quatro ingressos.'],
    hino: ['As câmeras mostraram você sem cantar o hino na seleção. A internet não perdoou.', 'Você ficou calado no hino da seleção e a imagem rodou o país.'],
    arbitro_foto: ['Vazou uma foto sua jantando com o árbitro do próximo clássico.', 'Uma foto sua num jantar com o árbitro do clássico caiu nas redes.'],
    drone: ['Um drone filmou o treino fechado e revelou a escalação do clássico.', 'Treino secreto, só que não: um drone sobrevoou o CT e filmou tudo.'],
    cartola: ['Dois milhões de pessoas te escalaram no fantasy e você fez pontuação negativa.', 'Você foi o jogador mais escalado do fantasy da rodada e terminou no negativo.'],
    palco: ['Uma dupla famosa quer você cantando uma música no show de domingo.', 'Convite para subir no palco e cantar com uma dupla famosa no fim de semana.'],
    tatuagem: ['Você prometeu numa entrevista tatuar o escudo se fosse campeão. E foi campeão.', 'A promessa está gravada em vídeo: título é igual a escudo tatuado. O título veio.'],
    penteado: ['O seu novo corte de cabelo virou pauta em todos os programas esportivos.', 'Mudou o cabelo e o país inteiro comentou. Os programas esportivos não falam de outra coisa.'],
    sosia: ['Um sósia seu anda dando autógrafos e entrando de graça nas festas.', 'Tem um cara muito parecido com você se passando por você na cidade.'],
    figurinha: ['Sua figurinha é a mais difícil do álbum. Pais te param na rua pedindo uma.', 'Ninguém acha a sua figurinha. Virou caça ao tesouro nas escolas.'],
    namoro: ['Você está namorando uma cantora famosa e os paparazzi não desgrudam.', 'O namoro com uma cantora famosa virou assunto, e os fotógrafos estão em toda parte.'],
    idioma: ['Você tentou falar o idioma local na coletiva e disse que "ama o goleiro adversário".', 'Coletiva no idioma novo: você quis elogiar e acabou declarando amor ao goleiro rival.'],
    mae_entrevista: ['Sua mãe contou na TV que você dormia abraçado na bola e chorava ao perder no videogame.', 'Entrevista da sua mãe na TV: histórias de infância que você preferia esquecer.'],
    pai_arquibancada: ['Seu pai discutiu com torcedores que te xingavam, e o vídeo viralizou.', 'Confusão na arquibancada: seu pai brigou com quem te ofendia e foi filmado.'],
    cueca: ['Doze jogos invicto com a mesma cueca da sorte. Ela rasgou no treino.', 'A cueca da sorte, que acompanhou doze jogos sem derrota, rasgou.'],
    benzedeira: ['Sua avó mandou uma benzedeira para o CT antes da decisão. Ela está na portaria.', 'Véspera de decisão e a benzedeira da sua avó apareceu no CT, com galho de arruda na mão.'],
    trofeu_sumido: ['A taça sumiu na festa do título. A última foto dela é com você.', 'Depois da festa do título, ninguém acha a taça. A última imagem dela está no seu celular.'],
    apelido: ['O elenco te deu um apelido ridículo e a torcida comprou a ideia. Já tem faixa.', 'Um apelido bobo do vestiário pegou na arquibancada. Até cantam.'],
    grito_torcida: ['A torcida criou uma música para você, mas a letra ofende o rival.', 'Tem música nova com o seu nome na arquibancada. O problema é a parte que fala do rival.'],
    presente_torcedor: ['Um sócio de 80 anos te deu o relógio que ganhou por 50 anos de clube.', 'Um torcedor antigo quer que você fique com o relógio que ganhou pelos 50 anos de sócio.'],
    clausula: ['A imprensa descobriu que a sua multa rescisória é baixa. Três clubes já se mexeram.', 'Vazou o valor da sua cláusula de rescisão: barata. E os clubes perceberam.'],
    gol_contra: ['Você fez um gol contra de calcanhar no clássico, e o vídeo bateu vinte milhões de visualizações.', 'Gol contra de calcanhar no clássico. A internet transformou em meme mundial.'],
    xerife: ['Mais um cartão e você está fora do clássico. E você leva cartão quase todo jogo.', 'Pendurado: o próximo amarelo te tira do clássico.'],
    luvas: ['Uma marca mandou luvas personalizadas, mas o modelo é diferente do que você usa há anos.', 'Chegaram luvas novas com o seu nome bordado. O corte é diferente do seu modelo de sempre.'],
    penalti_goleiro: ['Disputa de pênaltis na copa: os cinco batedores já foram. O técnico olha para você.', 'Pênaltis alternados, e só sobrou o goleiro para bater. O técnico aponta para você.'],
    assistencia_roubada: ['O site de estatísticas deu a sua assistência para o lateral. Foi sua, sem dúvida.', 'Roubaram sua assistência: as estatísticas oficiais creditaram o passe ao lateral.'],
    maestro: ['O técnico quer você mais recuado, organizando o jogo à frente da zaga.', 'Nova função proposta: primeiro volante, ditando o ritmo lá de trás.'],
    gol_mao: ['Você marcou com a mão e o árbitro deu o gol. O jogo segue.', 'A bola entrou depois de bater na sua mão. O árbitro validou.'],
    artilharia: ['Falta um gol para a artilharia, e a final da copa é em três dias. O técnico quer te poupar.', 'Um gol separa você da artilharia. Mas a final é daqui a três dias, e o técnico pensa em descanso.'],
    grisalho: ['Um fio branco apareceu na sua barba e a internet não perdoou.', 'A câmera pegou o primeiro fio branco na sua barba. Virou assunto.'],
    comentarista: ['Uma emissora quer você comentando, nas folgas, os jogos que não disputa.', 'Convite de uma TV: comentar partidas nos seus dias de folga.'],
    estatua: ['O clube vai fazer uma estátua sua na porta do estádio. O escultor pede quarenta sessões de pose.', 'Estátua confirmada na entrada do estádio. Só falta posar, e são quarenta sessões.'],
    oculos: ['O oftalmologista do clube descobriu que você enxerga mal de longe. Há anos.', 'Exame de rotina e uma surpresa: sua visão para longe é ruim, e faz tempo.'],
    teste_fisico: ['Você ficou em último no teste de corrida da pré-temporada, e a imprensa descobriu.', 'Último lugar no teste físico. O resultado vazou para os jornais.'],
    dirigente: ['O presidente oferece um cargo de diretor depois da aposentadoria, e já quer sua opinião nas contratações.', 'Proposta para o futuro: diretoria do clube. E o presidente quer que você comece a ajudar já.'],
    turne: ['Os clubes por onde você passou querem te homenagear quando você jogar lá.', 'Turnê de despedida: cada ex-clube prepara uma homenagem para a sua visita.'],
    palestra: ['Empresas querem pagar caro por palestras suas. Já são dez datas na agenda.', 'O mercado de palestras descobriu você: dez convites bem pagos.'],
  };
})();
