// Nas redes: textos dos posts do jogador e dos comentários (torcida, haters, clube, páginas e famosos).
// Tudo fictício, para a simulação. Marcadores:
//   {n} nome · {time} clube · {aoTime} "ao clube" · {doTime} "do clube" · {noTime} "no clube" · {num} número da camisa · {idade} idade · {cor} coração na cor do clube
//   temporada: {stat} (gols, assistências, desarmes ou jogos sem sofrer gol) · {jogos} · {nota} · {pos} posição na tabela
//              {naLiga} ("no Brasileirão", "na Premier League") · {pts} pontos · {titulos} títulos do ano
//   lance:     {min} minuto · {vs} adversário com artigo ("o Palmeiras") · {contraVs} ("contra o Palmeiras")
//   carreira:  {temps} ("12 temporadas") · {numeros} números da carreira por posição (gols e assistências; jogos sem sofrer gol...)
(function () {
  const D = window.CRAQUE_DATA;
  D.SOCIAL = {
    // ================= POSTS DO JOGADOR =================
    posts: {
      // Posts inteiros, por clima da temporada
      whole: {
        ballon: [
          'Bola de Ouro. Nem nos meus sonhos de moleque eu imaginei isso. Obrigado a todos que estiveram comigo! 🏆✨',
          'O moleque que jogava descalço na rua agora é o melhor do mundo. Mãe, a gente conseguiu! 🏆😭',
          'Melhor do mundo. Escrevi isso num caderno aos 10 anos. Hoje eu fecho esse caderno. 🏆',
          'Dedico essa Bola de Ouro a cada pessoa que disse que eu não ia chegar. Obrigado pela motivação 😂🏆',
          'Sem palavras. Só gratidão. E um espaço novo na estante de casa 🏆✨',
          'Bola de Ouro! Agora preciso aprender a fazer discurso em inglês 😅🏆',
          'Minha avó perguntou se a bola dourada dá pra jogar no quintal. Vó, não dá 😂🏆',
          'Ganhei a Bola de Ouro e meu irmão ainda diz que no videogame eu sou ruim 🙄🏆',
          'Tem dia que a gente acorda e ainda não acredita. Hoje é um deles. Melhor do mundo! 🌍🏆',
          'Bola de Ouro com a camisa {num} {doTime}. Isso aqui é de vocês também, torcida {cor}',
        ],
        title: [
          'CAMPEÕES! 🏆 {titulos}. Temporada de muito trabalho. Obrigado, {time}!',
          'É campeão! 🏆 {stat} e uma taça pra guardar pra sempre. Obrigado, torcida!',
          'Pode soltar o grito que tá preso na garganta: É CAMPEÃO! 🏆🔥',
          'Taça na mão, sorriso no rosto e zero voz depois da festa 🏆🗣️',
          'Quem duvidou, segura essa! {titulos} é nosso! 🏆',
          'Mais uma pra galeria. E a de vocês, torcida, é a mais bonita {cor}🏆',
          'Dormi abraçado com a taça. Não me julguem 🏆😴',
          'Campeão! Agora a resenha vai até segunda-feira 🍖🏆',
          'Disseram que a gente não ia ganhar nada esse ano. Pois é 🤫🏆',
          'Meu pai chorou no telefone. Eu chorei no vestiário. A taça ficou intacta 😂🏆',
          'Levanta a taça, abraça o grupo, liga pra mãe. A ordem não importa 🏆{cor}',
          '{titulos}! Tem jogador que coleciona camisa. Eu tô colecionando taça 😎🏆',
          'Valeu cada treino debaixo de chuva. É campeão! 🌧️🏆',
          'O troféu é pesado. Carregar esse time no coração pesa mais, e eu adoro 🏆{cor}',
        ],
        great: [
          '{stat}. Temporada pra guardar na memória. Obrigado, {time}! 💪',
          'Que ano! {stat} e muito orgulho dessa camisa. Bora pra mais! 🔥',
          '{stat}. Trabalho em silêncio, resultado no gramado. 🤫⚽',
          'Fechando a temporada com {stat}. O segredo? Arroz, feijão e muito treino 🍚💪',
          'Eu só queria agradecer a Deus, à família e ao fisioterapeuta, que não teve folga nenhuma esse ano 😂🙏',
          'Temporada dos sonhos. {stat}. Ano que vem tem mais! 🚀',
          'Os números falam: {stat}. Eu só falo obrigado 🙏',
          'Nota {nota} na temporada. Meu professor de matemática nunca me deu isso 😂',
          '{jogos} jogos, {stat} e nenhuma vontade de parar. Que venha o próximo ano! 🔥',
          'Quando eu era criança, eu sonhava com uma temporada assim. Hoje eu só agradeço 🙏',
          'Ano especial com a {num}. Obrigado a cada companheiro que jogou do meu lado 🤝',
          'Disse que ia fazer a melhor temporada da carreira. Promessa é dívida 😎',
          'Fecho o ano feliz e cansado. Mais feliz que cansado 😅💪',
          'Ano bom é assim: a gente esquece do frio, das viagens e da saudade de casa. {stat}! 🙌',
        ],
        good: [
          '{stat}, uma temporada de entrega e muito orgulho de vestir essa camisa. Obrigado, {time}! 💪',
          'Temporada de evolução. {stat} e a certeza de que dá pra mais. 💪',
          'Nem tudo foi perfeito, mas teve muita entrega. {stat}. Seguimos! 🙌',
          'Fecho o ano com {stat} e a cabeça no próximo. Férias? Só uma semaninha 😅',
          'Ano bom, mas eu sou chato comigo mesmo: quero mais. Bora! 🔥',
          'Obrigado, {time}! Cada jogo com essa camisa vale a pena 💪',
          '{pos}º lugar {naLiga}. Dá pra subir e a gente vai subir 📈',
          'Temporada honesta. Agora é descansar a perna e voltar voando ✈️',
          'Nota {nota}. Bom, mas o meu boletim pede mais 📒😅',
          'Aprendi muito esse ano. O próximo vai ser pra colocar tudo em prática 💪',
          'Mais um ano vestindo a {num}. Que privilégio 🙏',
          'Saldo positivo! E a minha mãe aprovou, o que é o mais importante 😂',
        ],
        bad: [
          'Não foi a temporada que eu queria. Vou trabalhar em dobro pra voltar mais forte. 🙏',
          'Ano abaixo do que eu espero de mim. Cabeça no lugar e trabalho. 💪',
          'Tem ano que a bola não entra. Esse foi um deles. O próximo vai ser diferente. 🙏',
          'Li todas as críticas. Algumas foram justas. Outras foram da minha tia 😅 Bora reagir!',
          'Peço desculpas pelo ano. Prometo voltar com fome. 🍽️⚽',
          'Fase ruim? Sim. Fim da linha? Nem de longe. 💪',
          'Nota {nota}. Não é o meu padrão e eu sei disso. Vou buscar o meu nível de volta 🔙',
          'Desliguei o celular por uma semana. Voltei com uma ideia só: treinar 💪',
          'Quem tá comigo no ano ruim vai comemorar comigo no ano bom. Anota aí 📝',
          'Errei mais do que acertei. Assumo. E começo de novo amanhã às 7h ⏰',
          'Meu cachorro foi o único que não me criticou esse ano 🐶 Obrigado, parceiro',
          'Ano pra aprender. Lição anotada, lição aprendida 📚',
        ],
        bench: [
          'Poucos minutos esse ano, mas sigo trabalhando todo dia. Minha hora vai chegar. 💪',
          'Banco é lugar de descanso. Eu prefiro o gramado. Seguimos treinando! 🔥',
          'Conheci cada detalhe do banco de reservas esse ano. Agora quero conhecer o gramado de novo 😅',
          'Paciência e treino. Quando a chance vier, eu tô pronto. 🙏',
          'Ano de muito aprendizado vendo de fora. Ano que vem é de dentro. 💪',
          'Aqueci tanto esse ano que dava pra correr uma maratona 🏃 Bora jogar mais!',
          'O banco é confortável, mas não é o meu lugar. Tô treinando pra mostrar isso 💪',
          'Meu colete de reserva já tem até o meu cheiro 😂 Ano que vem eu quero a camisa',
          'Torci muito pelos companheiros. Agora quero que eles torçam por mim em campo 🙏',
          'Não reclamo. Treino. Quem treina, uma hora joga 💪',
        ],
        injury: [
          'Ano difícil, longe dos gramados. Obrigado pelo carinho de todos. Já já tô de volta! 🙏',
          'Fisioterapia, gelo e muita paciência. Volto mais forte, prometo. 💪',
          'O corpo pediu uma pausa. A cabeça já tá no próximo jogo. 🙏',
          'Obrigado aos médicos e fisioterapeutas. Vocês viram mais de mim esse ano do que a minha família 😂',
          'Lesão não escolhe hora. Mas eu escolho como voltar: melhor. 💪',
          'Já conheço cada aparelho do departamento médico pelo nome 😅 Bora voltar!',
          'Assisti mais jogo esse ano do que comentarista. Agora quero jogar 📺⚽',
          'A recuperação é um jogo também. E esse eu tô ganhando 💪',
          'Cada sessão de fisioterapia é um passo de volta pro gramado. Falta pouco 🙏',
          'Muletas devolvidas! Próxima parada: o gramado 🩼⚽',
        ],
        down: [
          'Dói demais. Peço desculpas à torcida. A gente vai voltar. 💔',
          'Rebaixamento é a pior sensação do futebol. Assumo a minha parte. 💔',
          'Hoje não tem frase bonita. Só tristeza e a promessa de reconstruir. 🙏',
          'Desculpa, torcida. Vocês mereciam mais. 💔',
          'Caímos. Não tem desculpa. Tem trabalho pela frente 💪',
          '{time} é maior que esse momento. Vai voltar. 🙏',
          'Silêncio, reflexão e trabalho. É o que eu prometo 🤐',
          'Noite triste. Mas a história de um clube não termina num rebaixamento 💔',
        ],
      },
      // Posts montados por partes (abertura + fato + fecho, às vezes com hashtags), para temporadas ótima, boa e fraca
      parts: {
        open: {
          up: ['Que ano!', 'Fechou!', 'Missão cumprida.', 'Temporada encerrada.', 'Olha onde a gente chegou.', 'Ano pra guardar.', 'Último jogo do ano, e que ano.',
            'Respira.', 'Agradecido.', 'Chegou a hora de descansar.', 'Pensa num ano bom.', 'Antes de tudo: obrigado.', 'Rapaziada, que temporada.', 'Mais um capítulo.', 'Fim de temporada.', 'Coração cheio.'],
          down: ['Ano difícil.', 'Não foi fácil.', 'Temporada encerrada.', 'Hora de refletir.', 'Nem sempre dá certo.', 'Sendo sincero:', 'Vou ser direto:', 'Ano de aprendizado.', 'Fim de temporada.', 'Cabeça erguida.'],
        },
        fact: {
          up: ['{stat} na temporada.', '{stat} em {jogos} jogos.', 'Nota {nota} e {stat}.', '{pos}º lugar {naLiga}, com {pts} pontos.', '{stat} e muita entrega.',
            '{jogos} jogos com a camisa {num}.', '{stat}, e eu ainda acho pouco.', 'Nota {nota} e a sensação de dever cumprido.', '{stat}, cada um com uma história.', '{pos}º lugar {naLiga} e {stat}.',
            'Aos {idade} anos, {stat}.', '{stat}. Sim, eu contei um por um 😂', '{jogos} jogos, zero arrependimento.', 'Nota {nota}. Meu pai mandou print pra família inteira.'],
          down: ['Nota {nota}, abaixo do que eu espero de mim.', '{pos}º lugar {naLiga} não é o lugar desse time.', '{jogos} jogos e muita coisa pra melhorar.', 'A nota {nota} não mente.',
            'Não consegui ajudar como queria.', 'Foi um ano de poucos acertos.', 'Ficamos em {pos}º. Não dá.', 'Faltou eu decidir mais.'],
        },
        close: {
          up: ['Obrigado, {time}! {cor}', 'Bora pra próxima! 🔥', 'Seguimos! 💪', 'Gratidão, Deus! 🙏', 'Obrigado, torcida! {cor}', 'Que venha o próximo ano! 🚀', 'Partiu férias (curtas) 🏖️',
            'Valeu, família! 🏠', 'Tamo junto, grupo! 🤝', 'E ainda tem muito mais! 😎', 'Isso é só o começo. 📈', 'Descansa, perna. Ano que vem tem mais 🦵', 'Orgulho de vestir a {num}! {cor}', 'Obrigado a todo mundo que acreditou 🙌', 'Agora é churrasco 🍖', 'Te amo, futebol ⚽{cor}'],
          down: ['Vou voltar mais forte. 💪', 'Desculpa, torcida. 🙏', 'Ano que vem é outro papo. 🔥', 'Trabalho, trabalho e trabalho. 💪', 'Obrigado a quem ficou do meu lado. 🙏', 'Cabeça erguida e bola pra frente. ⚽',
            'Promessa: vocês vão ver outro jogador. 📝', 'A virada começa amanhã. ⏰', 'Conto com vocês. {cor}', 'Bora reagir! 🔥', 'Seguimos juntos. 🤝', 'Não acabou. 💪'],
        },
        tags: {
          up: ['#Foco', '#Trabalho', '#VamosJuntos', '#Gratidão', '#Família', '#SóOComeço', '#MissãoCumprida', '#SempreMais', '#Camisa{num}', '#NoLimite', '#Bora', '#Deus', '#Climbix', '#RumoAoTopo', '#Resenha', '#Fome', '#DoBairroProMundo', '#Raiz', '#Treino', '#Orgulho'],
          down: ['#Reação', '#Trabalho', '#Foco', '#VoltaPorCima', '#Fé', '#NãoDesisto', '#Aprendizado', '#JuntosSomosMaisFortes', '#Recomeço', '#ÉSóUmaFase'],
          bye: ['#Obrigado', '#Gratidão', '#Lenda', '#Fim', '#ObrigadoFutebol', '#ÚltimaDança', '#UmaVidaInteira', '#AtéLogo', '#Saudade', '#Camisa{num}'],
        },
      },
      eventOk: [
        'Decisão tomada, foco total no que importa: o campo. 💪', 'Mais um capítulo da história. Seguimos! 🙌', 'Dia importante hoje. Gratidão por tudo! 🙏',
        'Tudo certo por aqui. Agora é bola pra frente ⚽', 'Boas notícias pra quem torce por mim 😉', 'Quem me conhece sabe: eu escolho com o coração e com a cabeça. 💪',
        'Fase boa dentro e fora de campo. Obrigado, Deus! 🙏', 'Escolha feita. Agora é provar dentro de campo 💪', 'Semana movimentada, coração tranquilo 😌',
        'Contei pra minha mãe primeiro. Ela aprovou. Então tá aprovado 😂', 'Tem decisão que a gente toma pensando no futuro. Essa foi uma delas 📈',
        'Aceitei o desafio. Quem me conhece sabe que eu gosto de um 😏', 'Tudo resolvido. Bora focar no próximo jogo ⚽', 'Notícia boa merece post. Obrigado a todos 🙏',
        'Às vezes a melhor jogada acontece fora de campo 😉', 'Feliz com o que vem por aí 🚀',
      ],
      eventKo: [
        'Nem tudo sai como a gente planeja. Cabeça erguida e bola pra frente. 🙏', 'Dia difícil. Aprendizado e sigo em frente. 💪', 'Errar faz parte. Insistir no erro, não. Bora! 🔥',
        'Semana complicada. Obrigado a quem mandou mensagem de apoio 🙏', 'Respira, treina e segue. 💪', 'Não saiu como eu queria. Acontece. Próximo! ⏭️',
        'Quem nunca tomou uma decisão errada que atire a primeira chuteira 👟😅', 'Lição aprendida. Da próxima vez, eu escuto a minha mãe 😂',
        'Dia ruim não define ninguém. Amanhã tem treino ⏰', 'Tropecei, mas não caí. Segue o jogo ⚽', 'Fica a lição. Fica o foco 💪', 'Nem todo dia é dia de vitória. Mas todo dia é dia de trabalho 🙏',
      ],
      transfer: [
        'Novo capítulo! Muito feliz de chegar {aoTime}. Vamos com tudo! ✍️', 'Assinado! ✍️ Obrigado pela confiança, {time}. Bora fazer história!',
        'Mala pronta, chuteira na mochila e muita vontade. Cheguei, {time}! 🧳⚽', 'Novo clube, mesmo sonho. Vamos juntos, {time}! 💪',
        'Já decorei o hino. Agora é jogar 😄 Obrigado, {time}!', 'Desafio aceito. Prazer, torcida {doTime}! {cor}', 'A {num} tá lavada e passada. Bora estrear, {time}! 👕',
        'Minha mãe já comprou a camisa nova. Então é oficial: agora jogo {noTime}! 😂', 'Nova casa, nova torcida, a mesma fome. Vamos, {time}! 🔥',
        'Primeiro dia {aoTime} e eu já me perdi no CT 😅 Feliz demais!', 'Sonho de criança: vestir essa camisa. Obrigado, {time}! 🙏',
        'Contrato assinado e caneta guardada de lembrança ✍️ Bora, {time}!', 'Deixo saudade por onde passei e chego com muita vontade. Vamos, {time}! 💪', 'Partiu! O próximo capítulo tem cor nova {cor}',
      ],
      momentOk: {
        goal: ['Que gol!', 'Bati e saí pro abraço!', 'Coração na boca e bola na rede!', 'Eu sabia que ia entrar!', 'Nem olhei pro goleiro, só bati!', 'Chutei com a alma!', 'Fechei o olho e confiei!', 'A bola sabia o caminho!'],
        save: ['Que defesa!', 'Fui buscar lá no canto!', 'Hoje não passou nada!', 'Li o batedor e fui!', 'Voei!', 'Luva abençoada!', 'Esperei até o último segundo!', 'Escolhi o canto certo!'],
        // Goleiro: o batedor chutou para fora (não foi defesa, então nada de "voei" ou "luva")
        saveFora: ['Fiquei grande no gol e ele mandou pra fora!', 'Encarei o batedor e a bola foi longe!', 'Segurei até o fim e ele errou o alvo!', 'Pressão no batedor: pra fora!'],
        tackle: ['Bola roubada no último minuto!', 'Carrinho limpo e jogo salvo!', 'Hoje não passou ninguém!', 'Cheguei na hora certa!', 'Tempo certo, carrinho perfeito!', 'Zaga fechada!', 'Desarme na raça!', 'Joguei a vida nesse carrinho!'],
        pass: ['Que passe!', 'Enfiei e ele só empurrou!', 'Vi a brecha e coloquei na medida!', 'Assistência com açúcar!', 'Passe de olho fechado!', 'Coloquei com a mão!', 'Ele correu, eu achei!', 'A bola foi de presente!'],
        // Estilo arriscado do lance (S.STYLES): chute forte, goleiro que adiantou, bote em pé, lançamento por cima
        goalB: ['Bati com tudo e a bola rasgou a rede!', 'Sem frescura: bomba e gol!', 'Pé na bola com raiva, goleiro nem viu!', 'Chutei forte porque colocado é pra quem tem tempo!', 'Explodi essa bola!', 'Nem mirei, só meti o pé!'],
        saveB: ['Saí da linha e cresci na frente dele!', 'Adiantei, encarei e peguei!', 'Fiquei gigante e a bola veio na minha mão!', 'Saí do gol na coragem e deu certo!'],
        tackleB: ['Fiquei em pé e a bola ficou comigo!', 'Encaixei o corpo e ele não passou!', 'Sem carrinho: só o corpo e a bola é minha!', 'Marquei em pé, do jeito que o professor ensina!'],
        passB: ['Lancei por cima e ele só empurrou!', 'Vi o goleiro adiantado e chapei por cima!', 'Lançamento com açúcar!', 'Bola por cima da zaga, na medida!'],
      },
      momentCtx: ["Aos {min}', {contraVs}.", "{min}' de jogo e decisão {contraVs}.", 'Último lance {contraVs}.', "Minuto {min}'.", 'Contra {vs}, no fim do jogo.', "Placar travado até os {min}'.", "Aos {min}'.", 'Na hora mais difícil, {contraVs}.'],
      momentEnd: {
        cup: ['É CAMPEÃO! 🏆', 'A taça é nossa! 🏆', 'Campeões da copa! 🏆', 'A copa vem pra casa! 🏆'],
        cont: ['É CAMPEÃO! 🏆', 'Campeões do continente! 🏆🌎', 'O continente é nosso! 🌎🏆', 'Taça continental na mão! 🏆'],
        title: ['O título é nosso! 🏆', 'Campeão da liga! 🏆', 'Liga conquistada na última rodada! 🏆', 'Título decidido no detalhe! 🏆'],
        acesso: ['ACESSO! 🚀', 'Subimos! 🚀', 'O acesso é nosso! 🚀', 'Subimos de divisão! 🚀'],
        classico: ['Clássico é clássico, e é nosso! 🔥', 'Clássico com a nossa cara! 🔥', 'Clássico é pra quem tem coragem! 🔥', 'A cidade é nossa! 🔥'],
      },
      momentTail: ['Isso aqui é pra vocês, torcida!', 'Dedico à minha família!', 'Que noite inesquecível!', 'Ninguém dorme hoje!', 'Arrepiado até agora!', 'Obrigado, Deus!',
        'Quero ver esse lance mil vezes!', 'Melhor sensação do mundo!', 'Mãe, eu falei que ia!', 'Vou lembrar disso pra sempre!', 'Grupo merece!', 'Coração ainda a mil!'],
      momentKo: [
        'Assumo a responsabilidade. Dói, mas vou voltar mais forte. 🙏', 'Não foi dessa vez. Obrigado pelo apoio de sempre, torcida. 💔', 'Eu queria muito dar essa alegria pra vocês. Desculpa. 💔',
        'Futebol às vezes é cruel. Mas eu volto. 🙏', 'Vou rever esse lance mil vezes. E na próxima, vai. 💪', 'A responsabilidade era minha e eu não consegui. Desculpa, torcida 💔',
        'Dormir hoje vai ser difícil. Amanhã tem treino 💪', 'Só erra quem tem coragem de tentar. Vou tentar de novo 🙏', 'Foi por pouco. E pouco, no futebol, é tudo 💔',
        "Aos {min}', {contraVs}, não deu. Dói. Mas eu volto 💪", 'Esse lance vai me perseguir uns dias. Depois vira combustível 🔥', 'Desculpa, grupo. Vocês mereciam mais 🙏',
      ],
      announce: [
        'Chegou a hora. Essa vai ser minha última temporada como jogador. Quero aproveitar cada jogo ao lado de vocês. Obrigado, futebol! ⚽🙏',
        'Última temporada. Vou jogar cada partida como se fosse a primeira. Obrigado por tudo! 🙏', 'Decidi: essa é a última dança. Bora fazer ela valer! 💃⚽',
        'Os joelhos mandaram um recado e eu resolvi ouvir 😅 Última temporada, vamos com tudo!', 'Aos {idade}, anuncio minha última temporada. Quero sair do jeito que entrei: com fome 🍽️⚽',
        'Contei pra família, pro grupo e agora pra vocês: esse é o meu último ano 🙏', 'Última temporada da camisa {num}. Bora encher o estádio! {cor}',
        'Ainda não pendurei a chuteira, mas já escolhi o prego 😂 Última temporada!', 'Vou parar. Mas antes, um último ano pra gente comemorar junto 🥂', 'Fim de uma era chegando. Aproveitem comigo cada jogo 🙌',
      ],
      farewell: [
        'Hoje eu me despeço dos gramados. {temps}, {numeros}. Obrigado, futebol. ⚽❤️', 'Fim. {temps} e uma vida inteira de gratidão. Obrigado a cada torcedor. 🙏',
        'Pendurei as chuteiras. Literalmente: tão na parede da sala agora 😂 Obrigado por tudo!', 'O menino que sonhava virou jogador. O jogador agora vira torcedor. Obrigado, futebol! ⚽❤️',
        '{numeros}. E milhões de abraços. Hoje eu paro. Obrigado! 🙏', 'Acabou. E foi lindo. Obrigado, família, companheiros e torcida {cor}',
        'Agora eu vou poder comer pizza na sexta sem culpa 🍕 Obrigado por tudo, futebol!', 'Última vez que eu entro em campo como jogador. Que privilégio foi viver isso 🙏',
        '{temps}. Nenhum arrependimento. Obrigado! ⚽', 'Fecho a porta do vestiário pela última vez. O coração fica lá dentro {cor}',
        'Me aposento hoje. Minha esposa pediu pra eu parar de comemorar gol na sala 😂 Obrigado, futebol!', 'Obrigado, bola. Você foi a minha melhor amiga ⚽❤️',
      ],
    },

    // ================= FAMOSOS =================
    // min: fama mínima para comentar. up = notícia boa, down = fase ruim, bye = despedida.
    // Opcionais: title (post de título ou Bola de Ouro) e up_GOL, up_ZAG, up_MEI, up_ATA (falas para a posição).
    // Cada um escreve como escreve no X de verdade: o bordão dele e uma piada, sem empilhar bordão.
    famous: [
      { h: 'craqueneto', name: 'Craque Neto', min: 30,
        up: ['Esse {n} eu paro pra assistir! Convoca, pelo amor de Deus!', 'Cascão, salva esse post! Eu falei desse menino primeiro!', 'Ei, garotinho! Joga muito, diga-se de passagem!',
          'Se o {n} repetir esse ano, eu apresento o programa de tanguinha. Tá gravado!', 'Joga mais que muito gringo que ganha em euro, pelo amor de Deus!',
          'Eu falei no programa e riram de mim. Quem ri agora? 😂', 'Menino de ouro! Agora fica longe de empresário ruim, hein!', 'Vocês tão de brincadeira comigo? Que jogador!'],
        down: ['Família não joga, {n}! Quem joga é você! Acorda!', 'Menos foto de carro e mais treino, garotinho!', 'Vocês tão de brincadeira comigo, né, {n}? Que ano foi esse?',
          'Cascão, tira os lances desse menino da tela! 😂', 'Eu defendo você no programa, mas assim fica difícil, garotinho!'],
        bye: ['Pelo amor de Deus, que carreira! Um dos maiores que eu vi! Obrigado, {n}!', 'Vem pro Donos da Bola! A cadeira do lado do Cascão é sua!', 'Esse {n} eu vou sentir falta. Esse {n} eu parava pra assistir!'],
        title: ['Campeão! E quem criticou, põe a cara na tela, Cascão! 🏆', 'Taça na mão! Agora renova com esse menino antes que um time árabe leve! 🏆'] },
      { h: 'casimiro', name: 'Casimiro', min: 30,
        up: ['Ih, meteu essa? 😂🔥', 'MUITO FORTE', 'chat, que isso', 'Simplesmente amassa. Apenas.', 'Tu tá de sacanagem comigo? 😂', 'Aceitas pix? Quero pagar o ingresso desse show 😂',
          'Qual é, tranquilão? 😎', 'Que papinho é esse de superestimado? Amassa! 😂', 'isso aqui é igual pastel de feira: não tem como não gostar 🥟', 'Apenas o {n} sendo o {n}.'],
        down: ['Que papinho, hein? 😂 Bora, reage!', 'Ih, mané... 😅 Ano que vem é outro papo', 'Tu tá de sacanagem comigo? Volta a amassar, mané!',
          'ano igual pizza fria: até dá pra comer, mas não era isso 🍕', 'chat, o {n} vai voltar. eu sinto essas coisas 🙏'],
        bye: ['Lenda. Simplesmente. Apenas. 🙏', 'Ih, meteu essa? Vai parar? Aceitas convite pra live? 📺', 'Tu tá de sacanagem comigo? Já vai? Muito forte essa carreira 🙏'],
        title: ['Ih, meteu essa? CAMPEÃO! Muito forte! 🏆', 'Campeão. Simplesmente. Apenas. 🏆😎', 'CAMPEÃO. Fecha a live. 🏆'] },
      { h: 'podpah', name: 'Podpah', min: 30,
        up: ['Brabo demais, mano! Vem pro Podpah contar essa 🎙️', 'É o pai! 🔥🔥', 'Papo reto: o {n} tá voando, mano!', 'Cê é loko, mano! Que fase!', 'O Mítico tá chorando aqui no estúdio vendo isso kkkk',
          'O episódio com o {n} vai bater recorde, certeza 🎙️📈', 'Mano, esse cara joga de chinelo e ainda é o melhor 😂', 'Mano, cada jogo desse cara vira corte 🎬'],
        down: ['Força, mano! Vem pro Podpah desabafar kkkk 🎙️', 'Cabeça erguida, mano, ano que vem é teu!', 'Mano, tu jogou de chinelo esse ano, mas a gente te ama kkkk 🙏', 'Mano, não liga pros comentários, papo reto 🙏'],
        bye: ['Lenda, mano! A cadeira do Podpah te espera 🎙️', 'É o pai pra sempre, mano! 🙌', 'Mano, agora tem tempo pra gravar 6 horas de episódio, hein 😂🎙️'] },
      { h: 'flowsportclub', name: 'Flow Sport Club', min: 30,
        up: ['Aí é cinema! 🎬', 'Olha o nível, rapaziada!', 'A resenha de hoje já tem pauta 😂🎙️', 'Rapaziada, alguém segura esse cara?', 'Enquete: o {n} é top 3 do país? 📊',
          'Rapaziada, o chat já tá pedindo o {n} na resenha 🎙️'],
        down: ['Fase ruim passa, rapaziada. Confia!', 'A resenha tá contigo, {n}!', 'Rapaziada, todo mundo tem ano ruim. Bora!'],
        bye: ['Resenha marcada pra contar essa história toda! 🎙️', 'Que carreira, rapaziada. Aí é cinema até o fim 🎬'] },
      { h: 'luvadepedreiro', name: 'Luva de Pedreiro', min: 30,
        up: ['RECEBA! 🙏⚽', 'Obrigado, meu Deus! Que fase do {n}! RECEBA!', 'Receeeeba! O {n} é monstro! 🙏', 'Receba, {n}! Receba! 🔥', 'Tá voando, irmão! RECEBA! 🙏'],
        down: ['Confia em Deus que vai dar certo, irmão! 🙏', 'Receba a força, {n}! 🙏', 'Deus tem um plano, irmão. Confia! 🙏'],
        bye: ['Obrigado, meu Deus, por essa carreira! RECEBA! 🙏', 'Receba o meu respeito, lenda! 🙏'] },
      { h: 'miltonneves', name: 'Milton Neves', min: 30,
        up: ['Grande {n}! Daqui a 30 anos vai estar no "Que fim levou?" como lenda 😄', 'Craque de verdade! Já anotei o nome pro "Que fim levou?" 📝',
          'Este comentário é um oferecimento de... brincadeira, {n}! Parabéns! 😄', 'Craque! E no meu site tem a ficha completa dele, desde o dente de leite 😄'],
        down: ['Ainda dá tempo de entrar pro "Que fim levou?" pela porta da frente, {n}! 😉', 'Calma, {n}. Todo craque tem ano ruim. Eu tenho a lista de todos 📋'],
        bye: ['Já separei o seu espaço no "Que fim levou?" 😂🙏', 'Que carreira! O "Que fim levou?" ganha um capítulo de ouro 📚'] },
      { h: 'galvaobueno', name: 'Galvão Bueno', min: 80,
        up: ['Haja coração, amigo! ❤️', 'Bem, amigos... que temporada do {n}!', 'Olha o {n}! Vai, {n}! Faz, {n}! Que fase! 🔥', 'Pra cima deles, {n}! Vambora!',
          'Pode isso, Arnaldo? Pode! 😂', 'Ronaldinho! Quer dizer... {n}! 😅 Que fase!'],
        up_GOL: ['Sai que é sua, {n}! Que temporada! 🧤', 'Sai que é sua, {n}! Haja coração! ❤️'],
        down: ['Calma, {n}! Calma! O futebol dá voltas.', 'Bem, amigos... nem sempre se ganha. Vambora!', 'Vamos ver, vamos ver... ano que vem é outra história!'],
        bye: ['Bem, amigos... uma carreira para a história. Obrigado, {n}! 🙏', 'Haja coração pra essa despedida! Obrigado, {n}!'],
        title: ['É campeão! É campeão! Haja coração! 🏆', 'Acabou! Acabou! É campeão! É do {n}! 🏆'] },
      { h: 'arnaldocoelho', name: 'Arnaldo Cezar Coelho', min: 80,
        up: ['A regra é clara: o {n} joga muito! 😂', 'A regra é clara: temporada nota 10!', 'Pode, Galvão. Pode! 😂', 'Revisei o lance três vezes. A regra é clara: craque ✅'],
        down: ['A regra é clara: tem que melhorar.', 'Lance revisado: dá pra fazer mais, {n} 🧐'],
        bye: ['A regra é clara: lenda! 🙏'] },
      { h: 'faustao', name: 'Faustão', min: 80,
        up: ['Ô loco, meu! Essa fera aí joga muito!', 'Quem sabe faz ao vivo! Parabéns, {n}! 👏', 'Ô loco, bicho! Que temporada!', 'Essa fera aí, meu! Olha que fera! 👏'],
        down: ['ERROU! 😂 Brincadeira, {n}, bola pra frente, meu!', 'Ô loco, meu, que ano complicado! Mas vai dar certo!', 'Calma, bicho! Acontece com todo mundo, até comigo no ar!'],
        bye: ['Ô loco, meu! Que carreira! Uma salva de palmas pra essa fera! 👏👏'] },
      { h: 'kaka', name: 'Kaká', min: 80,
        up: ['Que temporada! Segue firme e humilde 🙏👏', 'Visão de jogo não tem idade. Parabéns! 👏', 'Muito feliz pelo seu momento! Deus abençoe 🙏', 'Jogo bonito e elegante. Parabéns! 👏'],
        down: ['Momentos difíceis fazem parte. Confio muito em você 🙏', 'Cabeça no lugar. Você vai voltar 🙏', 'Já passei por lesões e fases ruins. Você vai sair mais forte 🙏'],
        bye: ['Uma carreira linda. Obrigado pelo futebol 🙏', 'Parabéns por tudo! Foi uma honra ver você jogar 👏'] },
      { h: 'ronaldinho', name: 'Ronaldinho', min: 80,
        up: ['Alegria demais te ver jogar, irmão! 😁⚽', 'Joga bonito sempre! 🤙', 'Que magia, irmão! 😁🤙', 'Isso é futebol arte! 🤙⚽', 'Bruxaria pura, irmão! 😁🧙'],
        down: ['Sorri, irmão! Futebol é alegria 😁🤙', 'Relaxa e se diverte, irmão 🤙', 'Bota um sorriso no rosto que a bola volta a obedecer 😁'],
        bye: ['Obrigado pelas jogadas, irmão! Agora é só alegria 😁🤙', 'Que carreira, irmão! Bora pro futevôlei agora 😁🏐'] },
      { h: 'romario', name: 'Romário', min: 80,
        up: ['Craque é craque. Tá no caminho certo 👊', 'Gostei. Muito bom.', 'Lembra eu. Mas eu era melhor 😎', 'Tá bom. Quando chegar nos mil, me avisa 😎', 'Parabéns, garoto. Continua assim e um dia chega perto 😎'],
        up_ATA: ['Centroavante tem que fazer gol. Esse faz. Gostei 👊', 'Dentro da área é ele e Deus. Igual eu 😎'],
        down: ['Tem que decidir mais. Simples assim.', 'Treina mais e posta menos. Depois a gente conversa.', 'Ano fraco. Acontece. Comigo não acontecia 😎'],
        bye: ['Grande jogador. Bem-vindo ao clube dos aposentados 😎', 'Carreira bonita. Quase tão boa quanto a minha 😎'] },
      { h: 'cafu', name: 'Cafu', min: 80,
        up: ['Capitão aprova! 💪', 'Que temporada, garoto! Segue assim 👏', 'Liderança dentro de campo. Gosto disso! 💪', 'Corre o campo todo e ainda decide. Parabéns! 👏'],
        down: ['Capitão que é capitão levanta o grupo. Levanta a cabeça, {n}! 💪', 'Ano difícil faz parte. Bora reagir 💪'],
        bye: ['Que carreira! O capitão aqui te aplaude de pé 👏', '100% gratidão por tudo que você fez pelo futebol 🙏'],
        title: ['100% Jardim Irene e 100% campeão! 🏆', 'Levanta essa taça bem alto, que eu sei como é! 🏆'] },
      { h: 'neymarjr', name: 'Neymar Jr', min: 150,
        up: ['Monstro demais, parceiro! 👏🔥', 'Tamo junto, mlk! Que fase! 🔥', 'Ousadia e alegria, parceiro! 🤙', 'Brabo! Vem jogar comigo no pôquer 😂🃏', 'Que isso, parceiro?! 🔥🔥'],
        down: ['Cabeça erguida, parceiro. Volta mais forte! 🙏', 'Já passei por isso, mlk. Vai dar certo! 💪', 'Não liga pra crítica, parceiro. Foca no seu 🙏'],
        bye: ['Gigante! Obrigado por tudo, parceiro. Lenda! 🐐', 'Que carreira, mlk! Bora jogar uma pelada de despedida 😁⚽'] },
      { h: 'vinijr', name: 'Vini Jr.', min: 150,
        up: ['Baila, {n}! 💃🔥', 'Que temporada, irmão! Bora! 🔥', 'Ninguém para, irmão! 🚀', 'Dança comigo na comemoração da próxima! 💃', 'Isso é futebol brasileiro! 🇧🇷🔥'],
        down: ['Segue firme, irmão. Ninguém para a gente 💪', 'Vai passar, irmão. Tamo junto 🙏', 'Cabeça erguida e baila de novo ano que vem 💃'],
        bye: ['Inspiração pra todos nós. Obrigado, lenda! 🙌', 'Uma última dancinha pra fechar com chave de ouro 💃🙏'] },
      { h: 'r9fenomeno', name: 'Ronaldo Fenômeno', min: 150,
        up: ['Fenômeno reconhece fenômeno 😄👏', 'Que fase! Aproveita cada momento 👏', 'Faz gol que nem eu: com o sorriso 😁', 'Joga demais! Parabéns 👏'],
        down: ['Lesão e fase ruim eu conheço bem. Você volta! 💪', 'Já voltei de coisa pior. Confia que dá 💪'],
        bye: ['Que carreira! Parabéns, {n} 👏', 'Bem-vindo à aposentadoria. A vida aqui é boa, pode vir 😄'] },
    ],

    // ================= TORCIDA, CLUBE, PÁGINAS E HATERS =================
    // Jeito do X de futebol: minúscula, kkkk, CAIXA ALTA quando empolga, meme, print, ratio e corneta.
    // Comentários que usam os dados do post (temporada, lance, transferência, despedida)
    ctx: {
      season: {
        up: ['NOTA {nota} E AINDA TEM GENTE QUE CRITICA', '{stat} e o cara ainda posta humilde. respeita', 'vi os {jogos} jogos. todos. minha esposa pediu o divórcio no meio do caminho',
          'nota {nota}?? o sofascore tá devendo, merecia 10', 'fiz uma planilha com teus números. minha chefe achou que era trabalho 📊', 'coloca esses números no currículo e manda pra seleção 📄',
          'a {num} nunca foi tão bem usada 👕', '{pos}º {naLiga} e você foi o melhor do time de longe', 'temporada pra mostrar pros netos', 'eu sabia desde a pré-temporada. tenho print 📸 (não tenho)',
          '{stat}. só isso. só isso que eu tenho pra dizer', 'quem disse que era fogo de palha tá onde agora? 🤫'],
        down: ['nota {nota}? já vi pior, relaxa 😅 (vi no meu time de várzea)', '{pos}º {naLiga} não é a tua cara. ano que vem a gente sobe', 'o time não ajudou também, né? sejamos justos',
          'você foi o único que correu esse ano, sério', 'ano estranho, mas eu sei do que você é capaz', 'a torcida não esqueceu as temporadas boas', 'respira, descansa e volta. a {num} te espera',
          '{jogos} jogos, nota {nota}. tem coisa pra melhorar, mas tô contigo', 'nota {nota} mas o coração é 10 (o futebol é 6, mas o coração é 10)'],
      },
      moment: {
        up: ["EU TAVA NO ESTÁDIO NESSE LANCE AOS {min}' 😭😭", 'contra {vs} é sempre mais gostoso 😏', 'assisti esse lance 37 vezes já. 38 agora', "meu vizinho ouviu meu grito aos {min}' e veio perguntar se tava tudo bem kkkk",
          'desliguei a TV de nervoso e liguei de novo bem na hora 😂', 'esse lance vai passar no replay até 2090', 'chorei no sofá, no carro e no trabalho no dia seguinte 😭',
          "aos {min}'! meu coração não aguenta, {n}", 'pra quem disse que ele não decide jogo grande 🤫', 'o narrador perdeu a voz e eu também 🗣️',
          "aos {min}' eu tava no banheiro e perdi. odeio minha vida", '{vs} vai sonhar com esse lance hoje 😴', 'o narrador gritou, eu gritei, o vizinho gritou, o cachorro latiu'],
        down: ['acontece com os melhores, {n}. cabeça erguida', 'um lance não apaga tudo que você fez', "aos {min}' dói, mas a gente tá contigo", 'foi por um detalhe. a próxima é tua',
          'até os maiores erraram, irmão', 'contra {vs} a gente se vinga ano que vem 😤', 'o time inteiro tem culpa, não só você', 'não dormi também. mas ainda acredito',
          "aos {min}' doeu até em mim, que tava no sofá comendo pipoca"],
      },
      transfer: ['bem-vindo, {n}! já comprei a camisa {num} 👕', 'era o reforço que faltava!', 'diretoria acertou demais nessa, quem diria', 'seja bem-vindo à maior torcida que existe {cor}',
        'torcida antiga chorando e a nova comemorando 😂', 'primeiro jogo já tá na agenda', 'estreia quando? já quero ingresso 🎟️', 'contratação do ano, sem discussão',
        'vem fazer história, {n}! {cor}', 'já tô vendo você levantando taça aqui 🏆', 'nem acredito que você agora joga {noTime} 😍', 'li o anúncio 3 vezes pra ter certeza que não era montagem',
        'finalmente meu time contratou alguém que joga bola', 'a diretoria acertou uma. alguém anota a data'],
      bye: ['{temps} de alegria. obrigado por cada uma', 'cada jogo seu tem uma memória minha guardada', 'cresci te vendo jogar. agora vou envelhecer contando suas histórias 🥹',
        'vou guardar sua camisa {num} pra sempre', 'sem você o domingo vai ficar mais chato 😢', 'faz um jogo de despedida, por favor 🙏', 'a {num} tinha que ser aposentada junto com você',
        'o futebol fica mais chato a partir de hoje'],
    },
    fans: {
      up: [
        'nosso camisa {num}! fica pra sempre {cor}', 'que fase, {n}! obrigado por tudo', 'O MELHOR DO PAÍS E NÃO É NEM PERTO', 'craque dentro e fora de campo 👏',
        'renova até 2040 e manda a conta pra mim, diretoria 🙏', 'já comprei a camisa {num} pro meu filho. e pra mim. e pro meu pai', 'meu ídolo!!! responde aí 🙏🙏', 'MONSTRO MONSTRO MONSTRO 🔥',
        'te amo, {n}!!! (minha namorada que lute) 😂', 'o pai tá on 🔥', 'tô passando mal com esse homem jogando', 'cria demais',
        'cadê os que falavam que ele era bagre? 🤫', 'acabou pra vocês, haters', 'sem condições esse cara', 'eu quando ele pega na bola: 🧍 eu quando ele arranca: 🏃💨',
        'trocaria meu irmão por ele fácil. desculpa, irmão', 'meu salário é um dia do dele, mas a felicidade é a mesma', 'nunca pedi nada: fica até se aposentar {cor}',
        'tão chamando de "fase". fase é da lua, isso aqui é craque', 'te defendi no bar e ganhei a discussão. obrigado pelo argumento', 'isso aqui não é jogador, é investimento',
        'vou colocar o nome do meu filho de {n}. minha esposa ainda não sabe', 'o algoritmo me trouxe aqui e eu agradeço', 'ele é o motivo do meu pai voltar a sorrir no domingo',
        'coloquei seu nome no meu gato. ele é péssimo de bola, mas tudo bem 🐱', 'faltei aula pra te ver jogar. valeu a pena (mãe, se tiver lendo, é mentira)',
        'toda vez que você pega na bola eu grito VAI e assusto a família inteira', 'minha filha aprendeu a falar "{n}" antes de "papai" 😂', 'até minha sogra, que odeia futebol, sabe quem é você',
        'para de jogar tanto, tá deixando o resto do time feio 😂', 'o dia que você sair daqui eu paro de torcer. mentira, mas vou ficar triste', 'comprei ingresso só pra te ver aquecer',
        'isso aqui é craque de verdade, não é craque de internet', 'me dá sua chuteira de presente de aniversário? 🥺', 'printa e guarda: esse cara vai ser o melhor do mundo 📸',
        'ninguém tá falando o suficiente sobre esse cara', 'joga com a calma de quem tá no sofá e a gente no sofá sofrendo', 'mais completo que álbum de figurinha do meu primo',
        'EU AMO ESSE HOMEM (no sentido futebolístico, Débora)', 'tem jogador e tem o {n}', 'chamem o técnico da seleção pra ver isso aqui 👀',
      ],
      down: [
        'ano que vem é nosso, {n}! confia', 'tamo junto nas boas e nas ruins 🙏', 'volta mais forte, craque', 'ainda acredito em você, {n} 💪',
        'fase ruim todo mundo tem. a minha durou 2016 inteiro', 'a torcida tá contigo {cor}', 'bora reagir, camisa {num} 🔥', 'eu sigo te defendendo no grupo da família 😂🙏',
        'não liga pros haters, {n}', 'vai voltar a ser aquele de antes, eu sei', 'meu ídolo continua sendo meu ídolo {cor}', 'os craques também caem. a diferença é que eles levantam',
        'discuti com meu cunhado por sua causa. não me deixa na mão ano que vem 😂', 'treina, descansa e volta voando ✈️', 'ninguém esquece o que você já fez aqui',
        'desliga o celular, vai pra praia e volta com tudo 🏖️', 'torcida de verdade aparece na hora ruim. tô aqui {cor}', 'eu ainda acredito. meu cunhado não, mas eu sim',
        'fica, {n}. vai dar certo (eu acho)', 'tamo junto, mas joga bola, pfv 🙏', 'não é a fase, é o time. ok, é um pouco a fase', 'o time é um caos e cobram só dele. impressionante',
        'defendi você no grupo da família e perdi. volta logo pra eu ter razão', 'volta o {n} de dois anos atrás, sinto saudade dele', 'tirei teu nome da bio por enquanto. mas volto a colocar, prometo',
      ],
      bye: [
        'não vai não 😭😭', 'obrigado por tudo, {n}! eterno ídolo {cor}', 'chorei aqui 😭 que carreira', 'vou contar pros meus filhos que vi o {n} jogar 🥹',
        'volta, nem que seja pro jogo de despedida 😭', 'sem você o futebol fica mais chato 😢', 'LENDA LENDA LENDA 🐐', 'meu filho tem seu nome. sério 🥹',
        'pode virar técnico {doTime} agora? 👀', 'hoje é dia de chorar no banho 😭', 'um pedaço da minha infância se aposenta hoje 🥺', 'ainda dá tempo de mudar de ideia, viu?',
        'minha mãe chorou mais que eu, e ela nem gosta de futebol', 'que honra ter vivido a sua época', 'vou emoldurar o ingresso do seu último jogo 🖼️', 'fim de uma era 😢',
        'aposenta o jogador, mas não aposenta o ídolo {cor}', 'agora vai ter tempo pra responder os fãs, né? 👀',
      ],
    },
    // Comentários aleatórios que aparecem em qualquer post (a internet sendo a internet)
    random: [
      'primeiro 🥇', 'alguém em 2077 vendo isso?', 'sorteio? 👀', 'me segue de volta 🙏', 'quem veio pelo TikTok? 🙋', 'mãe, eu tô na internet!',
      'joga no meu time de várzea sábado? pago o churrasco 🍖', 'ainda tenho sua figurinha brilhante 🥹', 'comentei antes do Neto!', 'ganha 5 mil por dia? clica no link 😂',
      'só vim ver os comentários', 'responde que eu mostro pra minha sala inteira 🙏', 'ele leu meu comentário, eu sei', 'nem li, mas concordo', 'fui marcado aqui por engano?', 'cadê o Casimiro comentando?? 😂',
      'vende essa chuteira pra mim?', 'parabéns pelo aniversário! (não é hoje? ah, desculpa)', 'meu pai disse que joga mais que você 😂',
      'a legenda tá linda, foi o assessor que escreveu? 😂', 'quando vai lançar a biografia?', 'não gostei... amei! 😂', 'alguém sabe a senha do wi-fi do estádio?', 'vim pelo meme, fiquei pelo craque',
      'qual é o shampoo? pergunta séria', 'me adota? eu lavo a louça 🍽️', 'tô no trabalho fingindo que tô trabalhando e vendo seus posts', 'quem é você? (brincadeira, te amo)', 'desce o link da camisa',
      'meu horóscopo disse que hoje você ia postar. acertou ✨', 'se esse comentário tiver 100 curtidas eu raspo a cabeça', 'vim aqui dizer que meu time é melhor (mentira, vim te elogiar)',
      'alguém viu meu cachorro? é caramelo 🐕', 'segue a página do meu tio, ele vende açaí 🍧', 'chama no direct, tenho uma proposta de time de várzea', 'eu e meus 3 seguidores te apoiamos',
      'qual o segredo? brócolis?', 'vovó mandou um beijo 👵', 'já mostrei esse post pro meu chefe pra justificar a falta de ontem', 'vou fazer meu TCC sobre você', 'pior que eu ia comentar a mesma coisa',
      'grupo da família já tá discutindo esse post', 'me empresta 10 reais? 😂', 'alguém mais caiu aqui pelo algoritmo?', 'comentando pra engajar. nem sei quem é (mentira, sei sim)',
      'quem tá aqui antes do post viralizar 🙋', 'tô vendo isso na fila do banco', 'vim pela treta. cadê a treta?', 'meu tio que diz que futebol é perda de tempo curtiu esse post',
      'responde ou eu te vendo no meu modo carreira', 'eu: vou dormir cedo hoje. também eu, 2h da manhã, lendo os comentários desse post', 'kkkkkkkkkkkkkkk nem sei do que tô rindo mas tô',
      'o estagiário da página do clube tá on hoje', 'alguém traduz pra minha avó que ele é bom?',
      // spam, golpe e coisa nada a ver (acontece em todo post grande)
      '🚀 $CRAQUECOIN vai 100x essa semana! link na bio 🚀🌕', 'eu investia 200 reais e hoje tiro 8 mil por semana com o método do mentor @lucro.facil 💸', 'compre agora o token oficial do seu ídolo (não oficial) 🪙',
      'ganhei um iPhone só respondendo uma pesquisa, clica no meu perfil 📱', 'trader aos 19, milionário aos 20. quer saber como? 📈 link na bio',
      'promoção: seguidores brasileiros reais por R$ 9,90 🔥 DM', 'faço seu mapa astral de jogador por pix. hoje você está em Marte retrógrado ♂️',
      'vendo fogão 4 bocas seminovo, aceito troca por camisa autografada 🔥', 'bom dia, grupo! ops, achei que era o grupo da família', 'curso de oratória para jogadores, primeira aula grátis 🎤',
      'atenção: o perfil verdadeiro do craque está pedindo pix. NÃO É ELE. mas me manda um pix que eu confirmo 😇', 'renda extra: ganhe dinheiro comentando posts (tipo esse) 💰',
      'investi tudo em $GOLAÇO e agora moro com minha mãe de novo 🥲', 'alguém quer comprar um terreno na Lua? documentado 🌕', 'eu sou o primo dele de verdade, aceito doações',
      'esse post foi gerado por IA? pergunta honesta 🤖', 'tô vendendo ingresso pro próximo jogo, só não pergunta como consegui 🎟️', 'mãe, se você ler isso: eu tô bem, só não volto pra casa hoje',
    ],
    // Páginas de memes (verificadas, sem o nome de nenhuma página real): aparecem nos posts bons
    pages: [
      ['memes.da.bola', 'quando o {n} posta: "obrigado, Deus". quando eu posto: "boa noite, grupo" 😂'], ['bola.de.cristal', 'previsão: o {n} vai postar de novo na semana que vem 🔮'],
      ['resenha.esportiva', 'o post do {n} passou de mil comentários em 10 minutos e metade é gente pedindo pix 😂'], ['torcedor.noticias', 'torcida reage ao post do {n}: "ídolo", "renova" e "me segue de volta"'],
      ['jogadas.raras', 'lembram daquele lance do {n}? pois é. ele postou hoje 👇'], ['quadro.tatico', 'análise: o que o post do {n} diz sobre o próximo ano. spoiler: nada, mas vamos analisar 🧐'],
      ['memes.da.bola', 'o {n} postando e o adversário vendo: 👁️👄👁️'], ['futebol.sem.contexto', 'futebol sem contexto: o {n} sorrindo pro celular às 23h47'],
    ],
    // Contas de notícia do X ("🚨 |", "📊 |", "HERE WE GO"): falam do fato do post, por tipo
    newsHandles: ['central.da.bola', 'bastidores.fc', 'futebol.em.dados', 'mercado.da.bola', 'placar.urgente', 'boletim.fc', 'lance.a.lance', 'arquivo.da.bola'],
    news: {
      'season.up': ['📊 | {n} na temporada: {jogos} jogos, {stat} e nota média {nota}. Números de elite.', '🔥 | {n} encerra o ano com nota {nota} e é o assunto mais comentado do futebol hoje.',
        '🚨 | {stat} em {jogos} jogos. {n} fecha a temporada em alta e manda recado nas redes.', '📈 | {n} termina em {pos}º {naLiga} e entra na lista dos melhores do ano.'],
      'season.down': ['📉 | {n} fecha a temporada com nota {nota} em {jogos} jogos. Ano abaixo do esperado.', '👀 | Após temporada irregular, {n} usa as redes para mandar recado à torcida.',
        '📊 | {n} na temporada: {jogos} jogos e nota média {nota}. A torcida se divide nos comentários.'],
      'moment.up': ["🎥 | O lance do {n} aos {min}' {contraVs}. Que momento!", "🚨 | AOS {min}'! {n} decide {contraVs} e a torcida vai à loucura.",
        "Quem viu, viu. Quem não viu, tá aqui 👇 {n} aos {min}' {contraVs}."],
      'moment.down': ["😬 | O lance que tirou o sono do {n} {contraVs}.", '👀 | {n} se manifesta após lance decisivo {contraVs}.'],
      transfer: ['🚨 OFICIAL | {n} é o novo reforço {doTime}. Seja bem-vindo!', '✍️ | Contrato assinado: {n} agora veste a camisa {num} {doTime}.',
        'HERE WE GO 🚨 {n} {aoTime}, papéis assinados ✍️', '💰 | Bastidores: a ida do {n} {aoTime} foi a novela da janela. E acabou bem.'],
      bye: ['🙏 | {n} anuncia que vai pendurar as chuteiras. {temps}, {numeros}.', '🐐 | LENDA. {n} confirma o fim da carreira de jogador após {temps}.',
        '📊 | Os números de {n}: {numeros} em {temps}.'],
      event: ['👀 | {n} usa as redes após decisão fora de campo. A torcida se divide.', '🚨 | {n} se pronuncia nas redes e o assunto vai parar nos mais comentados.',
        'Bastidores: a decisão do {n} movimentou o vestiário nesta semana 🗣️'],
    },
    haters: {
      up: [
        'superestimado. pronto, falei 🤷', 'contra time grande eu quero ver...', 'esse post tá mais bonito que a temporada kkkk', 'no videogame eu faço melhor 🎮',
        'assessoria trabalhando bem, hein', 'meu sobrinho de 8 anos faria igual', 'quero ver repetir ano que vem 🤨', 'jogou bem, tá. mas aquele pênalti de 2 anos atrás eu não esqueci 😤',
        'mais marketing que futebol 🤷', 'contra time pequeno é fácil', 'quando jogar no meu time eu elogio', 'hype de youtuber', 'juiz ajudou em metade desses jogos aí',
        'tá bom, tá bom, mas e a Copa?', 'esse aí só aparece em foto 📸', 'meu time tem três iguais a ele no banco', 'joga bem, mas comemora feio', 'esperando o dia que ele erra pra eu voltar aqui 👀',
        'fez o mínimo e já quer estátua', 'em liga fraca até eu brilho', 'esse sorriso aí é de quem ganhou no VAR', 'mais um que vai sumir na primeira lesão', 'não me convenceu ainda 🤨',
        'em clássico ele some mais que meu ex 👻', 'tô guardando esse post pra quando ele perder 📸', 'comemorou como se tivesse ganhado a Copa kkkk', 'craque de PowerPoint',
        'com esse salário era obrigação fazer o dobro', 'o adversário jogou com 10 metade dos jogos, mas ok, parabéns', 'tá postando pra quem? pros 4 jogos bons que você fez?',
        'jogador de modo carreira: só funciona no fácil', 'chama três jogos bons de "temporada"', 'o sofascore precisa ser investigado', 'freguês do meu time, só lembrando 🤫',
        'joga muito... contra o lanterna', 'craque de highlight de 15 segundos', 'quero ver numa quarta à noite, com chuva, fora de casa', 'parabéns. agora volta pro seu tamanho',
      ],
      down: [
        'tá na hora de pendurar a chuteira 😴', 'salário alto pra pouca coisa...', 'postando em vez de treinar?', 'devolve o dinheiro do meu ingresso 😤',
        'esse aí só joga no Instagram', 'cadê o craque? só vejo o influencer', 'vende pro rival, eles merecem', 'pelo menos o cabelo tá bonito', 'desliga o celular e vai treinar',
        'já foi bom um dia. um dia.', 'se ele jogar ano que vem eu cancelo o sócio', 'meu avô de bengala corre mais', 'postou rápido, joga devagar', 'esse ano ele jogou de pantufa',
        'vou pedir reembolso da camisa {num}', 'pior que o técnico ainda escala', 'desaprendeu a jogar?', 'fase ruim ou jogador ruim? 🤔', 'o empresário dele é um gênio, isso sim',
        'cadê aquele que ia ser o melhor do mundo?', 'treino, que é bom, nada', 'esse ano foi um amistoso longo pra ele', 'a fase ruim já virou estilo de jogo',
        'vai culpar o gramado de novo?', 'teu futebol tá igual meu wi-fi: cai toda hora', 'se omitir em campo virou arte e você é o Picasso', 'ganha em euro e joga em centavo',
        'esse post tem mais curtida que o seu número de passes certos', 'a camisa {num} merecia um dono melhor', 'já te vi mais vezes no stories que no campo',
        'pipoqueiro profissional 🍿', 'chama o VAR pra achar o {n} em campo', 'devolve o salário em pix, por favor', 'meu tio de 50 anos na pelada de domingo rende mais',
        'a melhor jogada dele no ano foi esse post', 'chegou como reforço e virou reforço do adversário', 'o único drible do ano foi no repórter', 'torcida pagando ingresso pra ver isso 🤡',
        'ratio + nota baixa + vai treinar',
      ],
      bye: ['já foi tarde 🙄 (brincadeira, valeu, craque)', 'finalmente vai dar espaço pros novos', 'vai fazer falta... pros adversários 😂', 'aposentou tarde, mas aposentou',
        'vou sentir falta de reclamar de você 😢', 'mesmo eu, que sempre critiquei: obrigado', 'pena que eu torci contra a carreira toda e não adiantou 😂',
        'vai virar comentarista e errar tudo também? 😂', 'até que enfim, achei que ia jogar até os 50', 'respeito, mas aquele lance perdido eu levo pro túmulo',
        'tchau! agora meu time tem chance 😂', 'vou ter que achar outro pra secar', 'superestimado até na despedida', 'ok, ok... foi bom. mas só um pouco',
        'aposentou do futebol? achei que já tinha aposentado faz uns 3 anos', 'despedida mais emocionante que a carreira inteira'],
    },
    // Crítica de verdade (não é hater): aparece até nos posts bons, e mais quanto mais famoso o jogador
    critics: {
      season: ['{stat} é bonito, mas nos jogos grandes você sumiu', 'nota {nota} na média, mas teve jogo que você nem tocou na bola', 'boa temporada, mas dá pra mais. ainda acho que tá abaixo do que pode',
        'com esse elenco dava pra brigar por mais. faltou você decidir', 'números bons contra time pequeno. contra os grandes, nem tanto', 'gostei do ano, mas o segundo turno foi fraco demais',
        'bom ano, mas o salário pede mais que isso', 'ok, mas no clássico onde você tava?', 'temporada boa, atitude nem sempre. menos reclamação com o juiz',
        'fio rápido 🧵 nota {nota} em {jogos} jogos, mas metade veio no primeiro turno. dá pra mais'],
      title: ['campeão, ok. mas na final quem decidiu foi o time, não você', 'taça merecida, mas você jogou abaixo na reta final', 'título é do grupo. teve jogo que você atrapalhou mais que ajudou',
        'parabéns pelo {titulos}, mas com esse elenco era obrigação', 'ganhou, mas não convenceu. ano que vem quero ver jogar bonito'],
      ballon: ['Bola de Ouro com {stat}? teve gente que fez mais. política pura', 'mereceu? mais ou menos. o prêmio foi mais pelo marketing', 'melhor do mundo e não decidiu nenhum jogo grande da seleção. hmm',
        'respeito, mas eu votaria em outro', 'ganhou o prêmio, mas o melhor ano dele foi outro'],
      moment: ['decidiu, ok. mas até os {min} minutos tava apagado', 'lance lindo, mas foi o único do jogo', 'fez o dele, mas o time não pode depender de um lance só',
        'ótimo, mas não precisava ter deixado chegar nesse sufoco', 'o lance salva a noite, não salva a atuação'],
      transfer: ['pagaram caro demais. quero ver render', 'contratação boa, mas não encaixa no esquema do técnico', 'mais um que chega como craque. vamos ver no campo',
        'já vi esse filme: chega com festa, sai pela porta dos fundos', 'bom jogador, mas não era a prioridade do elenco'],
      event: ['menos assunto fora de campo e mais bola dentro, por favor', 'decisão estranha, mas vamos ver no que dá', 'tá aparecendo mais nas notícias do que nos melhores momentos',
        'escolha de quem pensa em si, não no time', 'ok, mas e o futebol? o último mês foi fraco', 'bonito no post. no campo eu quero ver'],
      bye: ['grande carreira, mas podia ter parado antes. os dois últimos anos foram difíceis', 'ídolo, sim. mas tem gente maior que ele na história do clube',
        'respeito, mas nunca foi decisivo na seleção', 'carreira linda, mas ficou faltando aquela taça grande', 'obrigado, mas a gente esquece rápido dos anos ruins, né?'],
    },
    // O jogador às vezes responde o hater
    replies: [
      'Te espero na próxima, parça 😘', 'Anotado. Obrigado pela motivação 🙏', 'Kkkkk depois a gente conversa no gramado', 'Tá bom, professor 😂', 'Vou mostrar pra minha mãe, ela vai adorar 😂',
      'Bom dia pra você também ☀️', 'Valeu pela audiência 📈', 'Salvei seu comentário pra ler depois do próximo título 📌', 'Com esse ânimo, quer ser meu preparador físico?',
      'Tô treinando, só parei pra te responder 😂', 'Uma hora você vira fã. Eu espero ⏳', 'Relaxa, ano que vem eu te dou motivo pra apagar isso',
      'Kkkkkkkk essa foi boa, admito', 'Se quiser, te mando um ingresso pra ver de perto', 'Meu avô também achava isso. Hoje é meu fã 😂', 'Paz e amor, irmão ✌️',
      'Respeito sua opinião. E discordo dela 😂', 'Esse comentário vai pro mural do vestiário 😂', 'Toma uma água, tá calor 💧',
      'Engraçado, você comenta tudo que eu posto. Fã ou obsessão? 🤔', 'Fala isso no estádio, não no anonimato 😉', 'Escreveu tudo isso e esqueceu de trabalhar hoje?',
      'Vai lá, campeão do sofá, que o controle tá chamando 🎮', 'Com essa leitura de jogo, você é técnico? Ah não, é comentarista de rede social',
      'Se crítica fizesse gol, você era artilheiro', 'Te bloquear dava trabalho, então vou só ganhar mesmo', 'Na próxima eu marco e tu apaga esse comentário, combinado?',
      'Engraçado que no domingo você tava gritando meu nome no estádio 👀', 'Vou printar e emoldurar quando for campeão 🖼️',
      'Coragem é comentar isso com foto de perfil de desenho', 'Aceito a crítica e aceito o pix também 😂', 'Tô com o print. Depois do título eu te marco 📸',
      'Mano, sua bio diz "pai de pet, coach e gratidão" e você tá aqui me xingando às 3h da manhã', 'Opa, vi seu perfil: 12 seguidores e 11 são bots. Abraço pros 11 🤖',
    ],
    club: {
      up: ['Orgulho de ter você com a nossa camisa! 💪', 'Que temporada, {n}! 👏', 'Esse é o nosso camisa {num}! 🔥', '{time} agradece, craque! 🙌',
        'Vem renovar logo que o presidente tá ansioso 😂✍️', 'Sim, a camisa {num} esgotou. Não, não temos previsão de reposição 😅', 'A casa é sua, {n}! 🏟️', 'Craque é craque {cor}',
        'O CT inteiro tá comentando esse post 😂', 'Bom dia pra quem tem o {n} 🌞', '{n} 🤝 deixar a gente feliz', 'O presidente leu e já foi procurar a caneta ✍️',
        'Nosso camisa {num} de novo nos assuntos do momento. Normal 💅', 'O roupeiro já separou a camisa do próximo jogo 👕'],
      down: ['Seguimos juntos, {n}. 🤝', 'Força, camisa {num}! Estamos contigo 💪', 'Família {time} unida! 🙌', 'O clube confia em você 🤝', 'Juntos, a gente vira essa página 💪',
        'Ano que vem é nosso, {n} {cor}', 'Treino amanhã às 9h. Bora! ⏰😉', 'Ninguém solta a mão de ninguém aqui 🤝'],
      bye: ['Obrigado por tudo, {n}. Sua história está escrita aqui. 🙌', 'Eterno camisa {num}. Obrigado! 👑', 'A camisa {num} vai ficar guardada com carinho 🙏', 'Seu lugar no museu do clube já está reservado 🏛️',
        'Uma lenda nunca sai de verdade. Obrigado, {n} {cor}', 'As portas {doTime} vão estar sempre abertas 🚪', 'Hoje o clube inteiro te aplaude de pé 👏'],
    },
    // Pessoas que comentam (torcida, internet, haters e críticos): nomes comuns no Brasil, montados em ui/social.js
    // como as pessoas se chamam no X ("Lucas", "Ana Clara ⚽", "gabi", "Pedro | Santos") com @ tirado do nome
    people: {
      first: ['Lucas', 'Gabriel', 'Matheus', 'Pedro', 'João Vitor', 'Guilherme', 'Rafael', 'Felipe', 'Thiago', 'Bruno', 'Diego', 'Vinícius', 'Caio', 'Enzo',
        'Davi', 'Arthur', 'Leo', 'Igor', 'Renan', 'Wesley', 'Kaique', 'Murilo', 'Henrique', 'Rodrigo', 'Marcos', 'Paulo', 'André', 'Fábio', 'Luiz', 'Juninho', 'Dudu',
        'Ana', 'Ana Clara', 'Gabi', 'Júlia', 'Bia', 'Larissa', 'Camila', 'Mari', 'Letícia', 'Duda', 'Isa', 'Carol', 'Fernanda', 'Jéssica', 'Nath', 'Vitória', 'Bruna', 'Lari', 'Rose', 'Cida'],
      last: ['Silva', 'Souza', 'Oliveira', 'Santos', 'Lima', 'Costa', 'Pereira', 'Ferreira', 'Almeida', 'Ribeiro', 'Carvalho', 'Rocha', 'Gomes', 'Martins', 'Barbosa', 'Araújo', 'Mendes', 'Freitas', 'Nunes', 'Moura'],
      deco: ['⚽', '🇧🇷', '🔥', '🙏', '✨', '🎮', '🍀'],
    },
    // Posts de evento (fora de campo): comentários sobre a escolha, não sobre a temporada.
    // up = a escolha deu certo; down = deu errado. Famosos usam evFamous com o próprio @.
    evFamous: {
      up: ['Atitude de quem sabe o que quer, {n} 👊', 'Gostei da postura, {n}.', 'É isso. Cabeça no lugar 👏', 'Decisão de gente grande. Segue firme, {n}!', 'Boa, {n}! Assim que se faz 👏'],
      down: ['Força, {n}. Acontece com todo mundo 🙏', 'Cabeça erguida, {n}. Isso passa.', 'Faz parte. Aprende e segue 👊', 'Tamo junto, {n}. Bola pra frente.', 'Erro todo mundo comete. O importante é a resposta, {n}.'],
    },
    evFans: {
      up: ['tamo junto, {n}! 🙌', 'que atitude. por isso é ídolo 👏', 'decisão certa demais', 'esse é o {n} que a gente gosta 💪', 'orgulho de torcer pra você {cor}', 'maturidade é outra coisa 👏',
        'sabia que ia dar certo!', 'isso que é cabeça boa 🧠', 'exemplo pros mais novos 👏', 'sigo fechado com você, {n}', 'o assessor de imagem merece aumento 😂', 'acertou em cheio. print e guarda'],
      down: ['força, {n}! a torcida tá contigo {cor}', 'acontece, bola pra frente 🙏', 'fica tranquilo, a gente confia em você', 'errou, mas assumiu. respeito 👊', 'vai dar a volta por cima 💪',
        'cabeça erguida, craque', 'não liga pros comentários não 🙏', 'todo mundo erra. volta mais forte', 'melhores dias virão, {n}', 'tamo junto na fase boa e na ruim {cor}',
        'deu ruim, mas a intenção foi boa (eu acho)'],
    },
    evHaters: {
      up: ['isso aí é assessoria, não decisão 🙄', 'post bonito. quero ver no campo', 'deu certo por sorte', 'menos marketing e mais bola', 'tá aparecendo mais fora de campo do que dentro',
        'acertou uma na vida e já quer palestra', 'até relógio parado acerta duas vezes por dia', 'queria que você decidisse jogo igual decide post', 'muito bonito. agora volta a jogar bola'],
      down: ['bem feito kkkk', 'pensa antes de agir da próxima vez 🤦', 'avisei que ia dar ruim', 'agora é tarde, {n}', 'quem mandou? 🤷',
        'inteligência zero, ousadia mil kkkk', 'decisão digna de quem cabeceia de olho fechado', 'nem o empresário te defende mais', 'coleciona escolha errada igual figurinha',
        'esse aí erra até no par ou ímpar', 'o assessor de imagem pediu demissão agora', 'era só não fazer. só isso. era só não fazer'],
    },
  };
})();
