// Nas redes: textos dos posts do jogador e dos comentários (torcida, haters, clube, páginas e famosos).
// Tudo fictício, para a simulação. Marcadores:
//   {n} nome · {time} clube · {aoTime} "ao clube" · {doTime} "do clube" · {noTime} "no clube" · {num} número da camisa · {idade} idade · {cor} coração na cor do clube
//   temporada: {stat} (gols, assistências, desarmes ou jogos sem sofrer gol) · {jogos} · {nota} · {pos} posição na tabela
//              {naLiga} ("no Brasileirão", "na Premier League") · {pts} pontos · {titulos} títulos do ano
//   lance:     {min} minuto · {vs} adversário com artigo ("o Palmeiras") · {contraVs} ("contra o Palmeiras")
//   carreira:  {temps} temporadas · {gols} gols · {assist} assistências
(function () {
  const D = window.CRAQUE_DATA;
  D.SOCIAL = {
    // ================= POSTS DO JOGADOR =================
    posts: {
      // Posts inteiros, por clima da temporada
      whole: {
        ballon: [
          'Bola de Ouro. Nem nos meus sonhos de moleque eu imaginei isso. Obrigado a todos que estiveram comigo! 🏆✨',
          'O moleque que jogava descalço na rua agora é o melhor do mundo. Mãe, a gente conseguiu! 🏆😭',
          'Melhor do mundo. Escrevi isso num caderno aos 10 anos. Hoje eu fecho esse caderno. 🏆',
          'Dedico essa Bola de Ouro a cada pessoa que disse que eu não ia chegar. Obrigado pela motivação 😂🏆',
          'Sem palavras. Só gratidão. E um espaço novo na estante de casa 🏆✨',
          'Bola de Ouro! Agora preciso aprender a fazer discurso em inglês 😅🏆',
          'Minha avó perguntou se a bola dourada dá pra jogar no quintal. Vó, não dá 😂🏆',
          'Ganhei a Bola de Ouro e meu irmão ainda diz que no videogame eu sou ruim 🙄🏆',
          'Tem dia que a gente acorda e ainda não acredita. Hoje é um deles. Melhor do mundo! 🌍🏆',
          'Bola de Ouro com a camisa {num} {doTime}. Isso aqui é de vocês também, torcida {cor}',
        ],
        title: [
          'CAMPEÕES! 🏆 {titulos}. Temporada de muito trabalho. Obrigado, {time}!',
          'É campeão! 🏆 {stat} e uma taça pra guardar pra sempre. Obrigado, torcida!',
          'Pode soltar o grito que tá preso na garganta: É CAMPEÃO! 🏆🔥',
          'Taça na mão, sorriso no rosto e zero voz depois da festa 🏆🗣️',
          'Quem duvidou, segura essa! {titulos} é nosso! 🏆',
          'Mais uma pra galeria. E a de vocês, torcida, é a mais bonita {cor}🏆',
          'Dormi abraçado com a taça. Não me julguem 🏆😴',
          'Campeão! Agora a resenha vai até segunda-feira 🍖🏆',
          'Disseram que a gente não ia ganhar nada esse ano. Pois é 🤫🏆',
          'Meu pai chorou no telefone. Eu chorei no vestiário. A taça ficou intacta 😂🏆',
          'Levanta a taça, abraça o grupo, liga pra mãe. A ordem não importa 🏆{cor}',
          '{titulos}! Tem jogador que coleciona camisa. Eu tô colecionando taça 😎🏆',
          'Valeu cada treino debaixo de chuva. É campeão! 🌧️🏆',
          'O troféu é pesado. Carregar esse time no coração pesa mais, e eu adoro 🏆{cor}',
        ],
        great: [
          '{stat}. Temporada pra guardar na memória. Obrigado, {time}! 💪',
          'Que ano! {stat} e muito orgulho dessa camisa. Bora pra mais! 🔥',
          '{stat}. Trabalho em silêncio, resultado no gramado. 🤫⚽',
          'Fechando a temporada com {stat}. O segredo? Arroz, feijão e muito treino 🍚💪',
          'Eu só queria agradecer a Deus, à família e ao fisioterapeuta, que não teve folga nenhuma esse ano 😂🙏',
          'Temporada dos sonhos. {stat}. Ano que vem tem mais! 🚀',
          'Os números falam: {stat}. Eu só falo obrigado 🙏',
          'Nota {nota} na temporada. Meu professor de matemática nunca me deu isso 😂',
          '{jogos} jogos, {stat} e nenhuma vontade de parar. Que venha o próximo ano! 🔥',
          'Quando eu era criança, eu sonhava com uma temporada assim. Hoje eu só agradeço 🙏',
          'Ano especial com a {num}. Obrigado a cada companheiro que jogou do meu lado 🤝',
          'Disse que ia fazer a melhor temporada da carreira. Promessa é dívida 😎',
          'Fecho o ano feliz e cansado. Mais feliz que cansado 😅💪',
          'Ano bom é assim: a gente esquece do frio, das viagens e da saudade de casa. {stat}! 🙌',
        ],
        good: [
          '{stat}, uma temporada de entrega e muito orgulho de vestir essa camisa. Obrigado, {time}! 💪',
          'Temporada de evolução. {stat} e a certeza de que dá pra mais. 💪',
          'Nem tudo foi perfeito, mas teve muita entrega. {stat}. Seguimos! 🙌',
          'Fecho o ano com {stat} e a cabeça no próximo. Férias? Só uma semaninha 😅',
          'Ano bom, mas eu sou chato comigo mesmo: quero mais. Bora! 🔥',
          'Obrigado, {time}! Cada jogo com essa camisa vale a pena 💪',
          '{pos}º lugar {naLiga}. Dá pra subir e a gente vai subir 📈',
          'Temporada honesta. Agora é descansar a perna e voltar voando ✈️',
          'Nota {nota}. Bom, mas o meu boletim pede mais 📒😅',
          'Aprendi muito esse ano. O próximo vai ser pra colocar tudo em prática 💪',
          'Mais um ano vestindo a {num}. Que privilégio 🙏',
          'Saldo positivo! E a minha mãe aprovou, o que é o mais importante 😂',
        ],
        bad: [
          'Não foi a temporada que eu queria. Vou trabalhar em dobro pra voltar mais forte. 🙏',
          'Ano abaixo do que eu espero de mim. Cabeça no lugar e trabalho. 💪',
          'Tem ano que a bola não entra. Esse foi um deles. O próximo vai ser diferente. 🙏',
          'Li todas as críticas. Algumas foram justas. Outras foram da minha tia 😅 Bora reagir!',
          'Peço desculpas pelo ano. Prometo voltar com fome. 🍽️⚽',
          'Fase ruim? Sim. Fim da linha? Nem de longe. 💪',
          'Nota {nota}. Não é o meu padrão e eu sei disso. Vou buscar o meu nível de volta 🔙',
          'Desliguei o celular por uma semana. Voltei com uma ideia só: treinar 💪',
          'Quem tá comigo no ano ruim vai comemorar comigo no ano bom. Anota aí 📝',
          'Errei mais do que acertei. Assumo. E começo de novo amanhã às 7h ⏰',
          'Meu cachorro foi o único que não me criticou esse ano 🐶 Obrigado, parceiro',
          'Ano pra aprender. Lição anotada, lição aprendida 📚',
        ],
        bench: [
          'Poucos minutos esse ano, mas sigo trabalhando todo dia. Minha hora vai chegar. 💪',
          'Banco é lugar de descanso. Eu prefiro o gramado. Seguimos treinando! 🔥',
          'Conheci cada detalhe do banco de reservas esse ano. Agora quero conhecer o gramado de novo 😅',
          'Paciência e treino. Quando a chance vier, eu tô pronto. 🙏',
          'Ano de muito aprendizado vendo de fora. Ano que vem é de dentro. 💪',
          'Aqueci tanto esse ano que dava pra correr uma maratona 🏃 Bora jogar mais!',
          'O banco é confortável, mas não é o meu lugar. Tô treinando pra mostrar isso 💪',
          'Meu colete de reserva já tem até o meu cheiro 😂 Ano que vem eu quero a camisa',
          'Torci muito pelos companheiros. Agora quero que eles torçam por mim em campo 🙏',
          'Não reclamo. Treino. Quem treina, uma hora joga 💪',
        ],
        injury: [
          'Ano difícil, longe dos gramados. Obrigado pelo carinho de todos. Já já tô de volta! 🙏',
          'Fisioterapia, gelo e muita paciência. Volto mais forte, prometo. 💪',
          'O corpo pediu uma pausa. A cabeça já tá no próximo jogo. 🙏',
          'Obrigado aos médicos e fisioterapeutas. Vocês viram mais de mim esse ano do que a minha família 😂',
          'Lesão não escolhe hora. Mas eu escolho como voltar: melhor. 💪',
          'Já conheço cada aparelho do departamento médico pelo nome 😅 Bora voltar!',
          'Assisti mais jogo esse ano do que comentarista. Agora quero jogar 📺⚽',
          'A recuperação é um jogo também. E esse eu tô ganhando 💪',
          'Cada sessão de fisioterapia é um passo de volta pro gramado. Falta pouco 🙏',
          'Muletas devolvidas! Próxima parada: o gramado 🩼⚽',
        ],
        down: [
          'Dói demais. Peço desculpas à torcida. A gente vai voltar. 💔',
          'Rebaixamento é a pior sensação do futebol. Assumo a minha parte. 💔',
          'Hoje não tem frase bonita. Só tristeza e a promessa de reconstruir. 🙏',
          'Desculpa, torcida. Vocês mereciam mais. 💔',
          'Caímos. Não tem desculpa. Tem trabalho pela frente 💪',
          '{time} é maior que esse momento. Vai voltar. 🙏',
          'Silêncio, reflexão e trabalho. É o que eu prometo 🤐',
          'Noite triste. Mas a história de um clube não termina num rebaixamento 💔',
        ],
      },
      // Posts montados por partes (abertura + fato + fecho, às vezes com hashtags), para temporadas ótima, boa e fraca
      parts: {
        open: {
          up: ['Que ano!', 'Fechou!', 'Missão cumprida.', 'Temporada encerrada.', 'Olha onde a gente chegou.', 'Ano pra guardar.', 'Último jogo do ano, e que ano.',
            'Respira.', 'Agradecido.', 'Chegou a hora de descansar.', 'Pensa num ano bom.', 'Antes de tudo: obrigado.', 'Rapaziada, que temporada.', 'Mais um capítulo.', 'Fim de temporada.', 'Coração cheio.'],
          down: ['Ano difícil.', 'Não foi fácil.', 'Temporada encerrada.', 'Hora de refletir.', 'Nem sempre dá certo.', 'Sendo sincero:', 'Vou ser direto:', 'Ano de aprendizado.', 'Fim de temporada.', 'Cabeça erguida.'],
        },
        fact: {
          up: ['{stat} na temporada.', '{stat} em {jogos} jogos.', 'Nota {nota} e {stat}.', '{pos}º lugar {naLiga}, com {pts} pontos.', '{stat} e muita entrega.',
            '{jogos} jogos com a camisa {num}.', '{stat}, e eu ainda acho pouco.', 'Nota {nota} e a sensação de dever cumprido.', '{stat}, cada um com uma história.', '{pos}º lugar {naLiga} e {stat}.',
            'Aos {idade} anos, {stat}.', '{stat}. Sim, eu contei um por um 😂', '{jogos} jogos, zero arrependimento.', 'Nota {nota}. Meu pai mandou print pra família inteira.'],
          down: ['Nota {nota}, abaixo do que eu espero de mim.', '{pos}º lugar {naLiga} não é o lugar desse time.', '{jogos} jogos e muita coisa pra melhorar.', 'A nota {nota} não mente.',
            'Não consegui ajudar como queria.', 'Foi um ano de poucos acertos.', 'Ficamos em {pos}º. Não dá.', 'Faltou eu decidir mais.'],
        },
        close: {
          up: ['Obrigado, {time}! {cor}', 'Bora pra próxima! 🔥', 'Seguimos! 💪', 'Gratidão, Deus! 🙏', 'Obrigado, torcida! {cor}', 'Que venha o próximo ano! 🚀', 'Partiu férias (curtas) 🏖️',
            'Valeu, família! 🏠', 'Tamo junto, grupo! 🤝', 'E ainda tem muito mais! 😎', 'Isso é só o começo. 📈', 'Descansa, perna. Ano que vem tem mais 🦵', 'Orgulho de vestir a {num}! {cor}', 'Obrigado a todo mundo que acreditou 🙌', 'Agora é churrasco 🍖', 'Te amo, futebol ⚽{cor}'],
          down: ['Vou voltar mais forte. 💪', 'Desculpa, torcida. 🙏', 'Ano que vem é outro papo. 🔥', 'Trabalho, trabalho e trabalho. 💪', 'Obrigado a quem ficou do meu lado. 🙏', 'Cabeça erguida e bola pra frente. ⚽',
            'Promessa: vocês vão ver outro jogador. 📝', 'A virada começa amanhã. ⏰', 'Conto com vocês. {cor}', 'Bora reagir! 🔥', 'Seguimos juntos. 🤝', 'Não acabou. 💪'],
        },
        tags: {
          up: ['#Foco', '#Trabalho', '#VamosJuntos', '#Gratidão', '#Família', '#SóOComeço', '#MissãoCumprida', '#SempreMais', '#Camisa{num}', '#NoLimite', '#Bora', '#Deus', '#Climbix', '#RumoAoTopo', '#Resenha', '#Fome', '#DoBairroProMundo', '#Raiz', '#Treino', '#Orgulho'],
          down: ['#Reação', '#Trabalho', '#Foco', '#VoltaPorCima', '#Fé', '#NãoDesisto', '#Aprendizado', '#JuntosSomosMaisFortes', '#Recomeço', '#ÉSóUmaFase'],
          bye: ['#Obrigado', '#Gratidão', '#Lenda', '#Fim', '#ObrigadoFutebol', '#ÚltimaDança', '#UmaVidaInteira', '#AtéLogo', '#Saudade', '#Camisa{num}'],
        },
      },
      eventOk: [
        'Decisão tomada, foco total no que importa: o campo. 💪', 'Mais um capítulo da história. Seguimos! 🙌', 'Dia importante hoje. Gratidão por tudo! 🙏',
        'Tudo certo por aqui. Agora é bola pra frente ⚽', 'Boas notícias pra quem torce por mim 😉', 'Quem me conhece sabe: eu escolho com o coração e com a cabeça. 💪',
        'Fase boa dentro e fora de campo. Obrigado, Deus! 🙏', 'Escolha feita. Agora é provar dentro de campo 💪', 'Semana movimentada, coração tranquilo 😌',
        'Contei pra minha mãe primeiro. Ela aprovou. Então tá aprovado 😂', 'Tem decisão que a gente toma pensando no futuro. Essa foi uma delas 📈',
        'Aceitei o desafio. Quem me conhece sabe que eu gosto de um 😏', 'Tudo resolvido. Bora focar no próximo jogo ⚽', 'Notícia boa merece post. Obrigado a todos 🙏',
        'Às vezes a melhor jogada acontece fora de campo 😉', 'Feliz com o que vem por aí 🚀',
      ],
      eventKo: [
        'Nem tudo sai como a gente planeja. Cabeça erguida e bola pra frente. 🙏', 'Dia difícil. Aprendizado e sigo em frente. 💪', 'Errar faz parte. Insistir no erro, não. Bora! 🔥',
        'Semana complicada. Obrigado a quem mandou mensagem de apoio 🙏', 'Respira, treina e segue. 💪', 'Não saiu como eu queria. Acontece. Próximo! ⏭️',
        'Quem nunca tomou uma decisão errada que atire a primeira chuteira 👟😅', 'Lição aprendida. Da próxima vez, eu escuto a minha mãe 😂',
        'Dia ruim não define ninguém. Amanhã tem treino ⏰', 'Tropecei, mas não caí. Segue o jogo ⚽', 'Fica a lição. Fica o foco 💪', 'Nem todo dia é dia de vitória. Mas todo dia é dia de trabalho 🙏',
      ],
      transfer: [
        'Novo capítulo! Muito feliz de chegar {aoTime}. Vamos com tudo! ✍️', 'Assinado! ✍️ Obrigado pela confiança, {time}. Bora fazer história!',
        'Mala pronta, chuteira na mochila e muita vontade. Cheguei, {time}! 🧳⚽', 'Novo clube, mesmo sonho. Vamos juntos, {time}! 💪',
        'Já decorei o hino. Agora é jogar 😄 Obrigado, {time}!', 'Desafio aceito. Prazer, torcida {doTime}! {cor}', 'A {num} tá lavada e passada. Bora estrear, {time}! 👕',
        'Minha mãe já comprou a camisa nova. Então é oficial: agora jogo {noTime}! 😂', 'Nova casa, nova torcida, a mesma fome. Vamos, {time}! 🔥',
        'Primeiro dia {aoTime} e eu já me perdi no CT 😅 Feliz demais!', 'Sonho de criança: vestir essa camisa. Obrigado, {time}! 🙏',
        'Contrato assinado e caneta guardada de lembrança ✍️ Bora, {time}!', 'Deixo saudade por onde passei e chego com muita vontade. Vamos, {time}! 💪', 'Partiu! O próximo capítulo tem cor nova {cor}',
      ],
      momentOk: {
        goal: ['Que gol!', 'Bati e saí pro abraço!', 'Coração na boca e bola na rede!', 'Eu sabia que ia entrar!', 'Nem olhei pro goleiro, só bati!', 'Chutei com a alma!', 'Fechei o olho e confiei!', 'A bola sabia o caminho!'],
        save: ['Que defesa!', 'Fui buscar lá no canto!', 'Hoje não passou nada!', 'Li o batedor e fui!', 'Voei!', 'Luva abençoada!', 'Esperei até o último segundo!', 'Escolhi o canto certo!'],
        tackle: ['Bola roubada no último minuto!', 'Carrinho limpo e jogo salvo!', 'Hoje não passou ninguém!', 'Cheguei na hora certa!', 'Tempo certo, carrinho perfeito!', 'Zaga fechada!', 'Desarme na raça!', 'Joguei a vida nesse carrinho!'],
        pass: ['Que passe!', 'Enfiei e ele só empurrou!', 'Vi a brecha e coloquei na medida!', 'Assistência com açúcar!', 'Passe de olho fechado!', 'Coloquei com a mão!', 'Ele correu, eu achei!', 'A bola foi de presente!'],
      },
      momentCtx: ["Aos {min}', {contraVs}.", "{min}' de jogo e decisão {contraVs}.", 'Último lance {contraVs}.', "Minuto {min}'.", 'Contra {vs}, no fim do jogo.', "Placar travado até os {min}'.", "Aos {min}'.", 'Na hora mais difícil, {contraVs}.'],
      momentEnd: {
        cup: ['É CAMPEÃO! 🏆', 'A taça é nossa! 🏆', 'Campeões da copa! 🏆', 'A copa vem pra casa! 🏆'],
        cont: ['É CAMPEÃO! 🏆', 'Campeões do continente! 🏆🌎', 'O continente é nosso! 🌎🏆', 'Taça continental na mão! 🏆'],
        title: ['O título é nosso! 🏆', 'Campeão da liga! 🏆', 'Liga conquistada na última rodada! 🏆', 'Título decidido no detalhe! 🏆'],
        acesso: ['ACESSO! 🚀', 'Subimos! 🚀', 'O acesso é nosso! 🚀', 'Subimos de divisão! 🚀'],
        classico: ['Clássico é clássico, e é nosso! 🔥', 'Clássico com a nossa cara! 🔥', 'Clássico é pra quem tem coragem! 🔥', 'A cidade é nossa! 🔥'],
      },
      momentTail: ['Isso aqui é pra vocês, torcida!', 'Dedico à minha família!', 'Que noite inesquecível!', 'Ninguém dorme hoje!', 'Arrepiado até agora!', 'Obrigado, Deus!',
        'Quero ver esse lance mil vezes!', 'Melhor sensação do mundo!', 'Mãe, eu falei que ia!', 'Vou lembrar disso pra sempre!', 'Grupo merece!', 'Coração ainda a mil!'],
      momentKo: [
        'Assumo a responsabilidade. Dói, mas vou voltar mais forte. 🙏', 'Não foi dessa vez. Obrigado pelo apoio de sempre, torcida. 💔', 'Eu queria muito dar essa alegria pra vocês. Desculpa. 💔',
        'Futebol às vezes é cruel. Mas eu volto. 🙏', 'Vou rever esse lance mil vezes. E na próxima, vai. 💪', 'A responsabilidade era minha e eu não consegui. Desculpa, torcida 💔',
        'Dormir hoje vai ser difícil. Amanhã tem treino 💪', 'Só erra quem tem coragem de tentar. Vou tentar de novo 🙏', 'Foi por pouco. E pouco, no futebol, é tudo 💔',
        "Aos {min}', {contraVs}, não deu. Dói. Mas eu volto 💪", 'Esse lance vai me perseguir uns dias. Depois vira combustível 🔥', 'Desculpa, grupo. Vocês mereciam mais 🙏',
      ],
      announce: [
        'Chegou a hora. Essa vai ser minha última temporada como jogador. Quero aproveitar cada jogo ao lado de vocês. Obrigado, futebol! ⚽🙏',
        'Última temporada. Vou jogar cada partida como se fosse a primeira. Obrigado por tudo! 🙏', 'Decidi: essa é a última dança. Bora fazer ela valer! 💃⚽',
        'Os joelhos mandaram um recado e eu resolvi ouvir 😅 Última temporada, vamos com tudo!', 'Aos {idade}, anuncio minha última temporada. Quero sair do jeito que entrei: com fome 🍽️⚽',
        'Contei pra família, pro grupo e agora pra vocês: esse é o meu último ano 🙏', 'Última temporada da camisa {num}. Bora encher o estádio! {cor}',
        'Ainda não pendurei a chuteira, mas já escolhi o prego 😂 Última temporada!', 'Vou parar. Mas antes, um último ano pra gente comemorar junto 🥂', 'Fim de uma era chegando. Aproveitem comigo cada jogo 🙌',
      ],
      farewell: [
        'Hoje eu me despeço dos gramados. {temps} temporadas, {gols} gols, {assist} assistências. Obrigado, futebol. ⚽❤️', 'Fim. {temps} temporadas e uma vida inteira de gratidão. Obrigado a cada torcedor. 🙏',
        'Pendurei as chuteiras. Literalmente: tão na parede da sala agora 😂 Obrigado por tudo!', 'O menino que sonhava virou jogador. O jogador agora vira torcedor. Obrigado, futebol! ⚽❤️',
        '{gols} gols, {assist} assistências e milhões de abraços. Hoje eu paro. Obrigado! 🙏', 'Acabou. E foi lindo. Obrigado, família, companheiros e torcida {cor}',
        'Agora eu vou poder comer pizza na sexta sem culpa 🍕 Obrigado por tudo, futebol!', 'Última vez que eu entro em campo como jogador. Que privilégio foi viver isso 🙏',
        '{temps} temporadas. Nenhum arrependimento. Obrigado! ⚽', 'Fecho a porta do vestiário pela última vez. O coração fica lá dentro {cor}',
        'Me aposento hoje. Minha esposa pediu pra eu parar de comemorar gol na sala 😂 Obrigado, futebol!', 'Obrigado, bola. Você foi a minha melhor amiga ⚽❤️',
      ],
    },

    // ================= FAMOSOS =================
    // min: fama mínima para comentar. up = notícia boa, down = fase ruim, bye = despedida.
    // Opcionais: title (post de título ou Bola de Ouro) e up_GOL, up_ZAG, up_MEI, up_ATA (falas para a posição).
    famous: [
      { h: 'craqueneto', min: 30,
        up: ['Esse {n} eu quero ver na Seleção! Esse {n} que eu amo, que eu paro pra assistir!', 'Ow Cascão, põe na tela aí os lances do {n}! Pelo amor de Deus!', 'Ei, garotinho! Joga muito, diga-se de passagem!',
          'Vocês tão de brincadeira comigo, né? Que temporada do {n}!', 'Se o {n} repetir esse ano, eu apresento o programa de tanguinha!', 'Pelo amor de Deus, que jogador! Diga-se de passagem, o melhor do campeonato!',
          'Eu falei aqui no programa: o {n} é craque! Eu falei!', 'Ow Cascão, deixa os lances do {n} no replay o programa inteiro!'],
        down: ['Vocês tão de brincadeira comigo, né, {n}? Que ano foi esse?', 'Família não joga, {n}! Quem joga é você! Acorda!', 'Pelo amor de Deus, {n}! Diga-se de passagem, eu esperava muito mais!',
          'Ei, garotinho, tá na hora de jogar bola, hein!', 'Ow Cascão, tira da tela, não quero nem ver! 😂'],
        bye: ['Pelo amor de Deus, que carreira! Diga-se de passagem, um dos maiores! Obrigado, {n}!', 'Ei, garotinho, vem pro Donos da Bola! A cadeira é sua!', 'Esse {n} eu vou sentir falta. Esse {n} que eu parava pra assistir!'],
        title: ['Campeão! Vocês tão de brincadeira comigo? Esse {n} é craque, pelo amor de Deus!', 'Ow Cascão, põe a taça na tela! É do {n}!'] },
      { h: 'casimiro', min: 30,
        up: ['Ih, meteu essa? 😂🔥', 'Muito forte, mané!', 'Simplesmente amassa.', 'Tu tá de sacanagem comigo? Que fase! 😂', 'Aceitas pix? Quero pagar o ingresso desse show 😂', 'Qual é, tranquilão? 😎',
          'Apenas o {n} sendo o {n}.', 'Que papinho é esse de que ele é superestimado? Amassa! 😂', 'O {n} é muito forte. Simplesmente.', 'Ih, mané... jogou demais!'],
        down: ['Que papinho, hein? 😂 Bora, reage!', 'Ih, mané... 😅 Ano que vem é outro papo', 'Tu tá de sacanagem comigo? Volta a jogar, mané!', 'Que papinho é esse de fase ruim, {n}? Acorda! 😂'],
        bye: ['Lenda. Simplesmente. Apenas. 🙏', 'Ih, meteu essa? Vai parar? Aceitas convite pra live? 📺', 'Tu tá de sacanagem comigo? Já vai? Muito forte essa carreira 🙏'],
        title: ['Ih, meteu essa? CAMPEÃO! Muito forte! 🏆', 'Campeão. Simplesmente. Apenas. 🏆😎'] },
      { h: 'podpah', min: 30,
        up: ['Brabo demais, mano! Vem pro Podpah contar essa 🎙️', 'É o pai! 🔥🔥', 'Papo reto: o {n} tá voando, mano!', 'Cê é loko, mano! Que fase!', 'Mano do céu! Monstro! 🔥', 'O episódio com o {n} vai bater recorde, certeza 🎙️📈',
          'Mano, esse cara joga de chinelo e ainda é o melhor 😂', 'Já separa a cadeira do estúdio pra ele, mano 🎙️'],
        down: ['Força, mano! Vem pro Podpah desabafar kkkk 🎙️', 'Cabeça erguida, mano, ano que vem é teu!', 'Pô, mano, acontece! Tamo junto!', 'Mano, não liga pros comentários, papo reto 🙏'],
        bye: ['Lenda, mano! A cadeira do Podpah te espera 🎙️', 'É o pai pra sempre, mano! 🙌', 'Mano, agora tem tempo pra gravar 3 horas de episódio, hein 😂🎙️'] },
      { h: 'flowsportclub', min: 30,
        up: ['Aí é cinema! 🎬', 'Olha o nível, rapaziada!', 'Isso é absurdo, rapaziada! 🔥', 'A resenha de hoje já tem pauta 😂🎙️', 'Rapaziada, alguém segura esse cara?', 'Esse aí já tem convite aberto pra resenha 🎙️'],
        down: ['Fase ruim passa, rapaziada. Confia!', 'A resenha tá contigo, {n}!', 'Rapaziada, todo mundo tem ano ruim. Bora!'],
        bye: ['Resenha marcada pra contar essa história toda! 🎙️', 'Que carreira, rapaziada. Aí é cinema até o fim 🎬'] },
      { h: 'luvadepedreiro', min: 30,
        up: ['RECEBA! 🙏⚽', 'Obrigado, meu Deus! Que fase do {n}! RECEBA!', 'Receeeeba! O {n} é monstro! 🙏', 'Receba, {n}! Receba! 🔥', 'Tá voando, irmão! RECEBA! 🙏'],
        down: ['Confia em Deus que vai dar certo, irmão! 🙏', 'Receba a força, {n}! 🙏', 'Deus tem um plano, irmão. Confia! 🙏'],
        bye: ['Obrigado, meu Deus, por essa carreira! RECEBA! 🙏', 'Receba o meu respeito, lenda! 🙏'] },
      { h: 'miltonneves', min: 30,
        up: ['Grande {n}! Daqui a 30 anos vai estar no "Que fim levou?" como lenda 😄', 'Craque de verdade! Já anotei o nome pro "Que fim levou?" 📝', 'Que temporada! Craque desse jeito eu não vejo todo dia 😄'],
        down: ['Ainda dá tempo de entrar pro "Que fim levou?" pela porta da frente, {n}! 😉', 'Calma, {n}. Todo craque tem ano ruim.'],
        bye: ['Já separei o seu espaço no "Que fim levou?" 😂🙏', 'Que carreira! O "Que fim levou?" ganha um capítulo de ouro 📚'] },
      { h: 'galvaobueno', min: 80,
        up: ['Haja coração, amigo! ❤️', 'Bem, amigos... que temporada do {n}!', 'Olha o {n}! Vai, {n}! Faz, {n}! Que fase! 🔥', 'Pra cima deles, {n}! Vambora!', 'Tá na hora de gritar: é do {n}!',
          'Pode isso, Arnaldo? Pode! 😂', 'Vamos ver, vamos ver... e o {n} resolveu de novo!'],
        up_GOL: ['Sai que é sua, {n}! Que temporada! 🧤', 'Sai que é sua, {n}! Haja coração! ❤️'],
        down: ['Calma, {n}! Calma! O futebol dá voltas.', 'Bem, amigos... nem sempre se ganha. Vambora!', 'Vamos ver, vamos ver... ano que vem é outra história!'],
        bye: ['Bem, amigos... uma carreira para a história. Obrigado, {n}! 🙏', 'Haja coração pra essa despedida! Obrigado, {n}!'],
        title: ['É campeão! É campeão! Haja coração! 🏆', 'Bem, amigos... é campeão! É do {n}! 🏆'] },
      { h: 'arnaldocoelho', min: 80,
        up: ['A regra é clara: o {n} joga muito! 😂', 'A regra é clara: temporada nota 10!', 'Pode, Galvão. Pode! 😂', 'Revisei o lance: foi golaço, a regra é clara ✅'],
        down: ['A regra é clara: tem que melhorar.', 'Lance revisado: dá pra fazer mais, {n} 🧐'],
        bye: ['A regra é clara: lenda! 🙏'] },
      { h: 'faustao', min: 80,
        up: ['Ô loco, meu! Essa fera aí joga muito!', 'Quem sabe faz ao vivo! Parabéns, {n}! 👏', 'Ô loco, bicho! Que temporada!', 'Essa fera aí, meu! Olha que fera! 👏'],
        down: ['Calma, meu! Acontece com todo mundo! Bola pra frente!', 'Ô loco, meu, que ano complicado! Mas vai dar certo!'],
        bye: ['Ô loco, meu! Que carreira! Uma salva de palmas pra essa fera! 👏👏'] },
      { h: 'kaka', min: 80,
        up: ['Que temporada! Segue firme e humilde 🙏👏', 'Visão de jogo não tem idade. Parabéns! 👏', 'Muito feliz pelo seu momento! Deus abençoe 🙏', 'Jogo bonito e elegante. Parabéns! 👏', 'Talento e trabalho. Que combinação! 👏'],
        down: ['Momentos difíceis fazem parte. Confio muito em você 🙏', 'Cabeça no lugar. Você vai voltar 🙏', 'Já passei por lesões e fases ruins. Você vai sair mais forte 🙏'],
        bye: ['Uma carreira linda. Obrigado pelo futebol 🙏', 'Parabéns por tudo! Foi uma honra ver você jogar 👏'] },
      { h: 'ronaldinho', min: 80,
        up: ['Alegria demais te ver jogar, irmão! 😁⚽', 'Joga bonito sempre! 🤙', 'Que magia, irmão! 😁🤙', 'Isso é futebol arte! 🤙⚽', 'Bruxaria pura, irmão! 😁🧙'],
        down: ['Sorri, irmão! Futebol é alegria 😁🤙', 'Relaxa e se diverte, irmão 🤙', 'Bota um sorriso no rosto que a bola volta a obedecer 😁'],
        bye: ['Obrigado pelas jogadas, irmão! Agora é só alegria 😁🤙', 'Que carreira, irmão! Bora pro futevôlei agora 😁🏐'] },
      { h: 'romario', min: 80,
        up: ['Craque é craque. Tá no caminho certo 👊', 'Gostei. Muito bom.', 'Lembra eu. Mas eu era melhor 😎', 'Fez o básico bem feito. Gol é isso.', 'Tá bom. Quando chegar nos mil, me avisa 😎'],
        up_ATA: ['Centroavante tem que fazer gol. Esse faz. Gostei 👊', 'Dentro da área é ele e Deus. Igual eu 😎'],
        down: ['Tem que decidir mais. Simples assim.', 'Treina finalização. Depois a gente conversa.', 'Ano fraco. Acontece. Comigo não acontecia 😎'],
        bye: ['Grande jogador. Bem-vindo ao clube dos aposentados 😎', 'Carreira bonita. Quase tão boa quanto a minha 😎'] },
      { h: 'cafu', min: 80,
        up: ['Capitão aprova! 💪', 'Que temporada, garoto! Segue assim 👏', 'Liderança dentro de campo. Gosto disso! 💪', 'Corre o campo todo e ainda decide. Parabéns! 👏'],
        down: ['Capitão que é capitão levanta o grupo. Levanta a cabeça, {n}! 💪', 'Ano difícil faz parte. Bora reagir 💪'],
        bye: ['Que carreira! O capitão aqui te aplaude de pé 👏', '100% gratidão por tudo que você fez pelo futebol 🙏'],
        title: ['100% Jardim Irene e 100% campeão! 🏆', 'Levanta essa taça bem alto, que eu sei como é! 🏆'] },
      { h: 'reymarjr', min: 150,
        up: ['Monstro demais, parceiro! 👏🔥', 'Tamo junto, mlk! Que fase! 🔥', 'Ousadia e alegria, parceiro! 🤙', 'Brabo! Vem jogar comigo no pôquer 😂🃏', 'Que isso, parceiro?! 🔥🔥', 'Joga muito, mlk! Tamo junto! 🤝'],
        down: ['Cabeça erguida, parceiro. Volta mais forte! 🙏', 'Já passei por isso, mlk. Vai dar certo! 💪', 'Não liga pra crítica, parceiro. Foca no seu 🙏'],
        bye: ['Gigante! Obrigado por tudo, parceiro. Lenda! 🐐', 'Que carreira, mlk! Bora jogar uma pelada de despedida 😁⚽'] },
      { h: 'vinijr', min: 150,
        up: ['Baila, {n}! 💃🔥', 'Que temporada, irmão! Bora! 🔥', 'Ninguém para, irmão! 🚀', 'Dança comigo na comemoração da próxima! 💃', 'Isso é futebol brasileiro! 🇧🇷🔥'],
        down: ['Segue firme, irmão. Ninguém para a gente 💪', 'Vai passar, irmão. Tamo junto 🙏', 'Cabeça erguida e baila de novo ano que vem 💃'],
        bye: ['Inspiração pra todos nós. Obrigado, lenda! 🙌', 'Uma última dancinha pra fechar com chave de ouro 💃🙏'] },
      { h: 'r9fenomeno', min: 150,
        up: ['Fenômeno reconhece fenômeno 😄👏', 'Que fase! Aproveita cada momento 👏', 'Faz gol que nem eu: com o sorriso 😁', 'Joga demais! Parabéns 👏'],
        down: ['Lesão e fase ruim eu conheço bem. Você volta! 💪', 'Já voltei de coisa pior. Confia que dá 💪'],
        bye: ['Que carreira! Parabéns, {n} 👏', 'Bem-vindo à aposentadoria. A vida aqui é boa, pode vir 😄'] },
    ],

    // ================= TORCIDA, CLUBE, PÁGINAS E HATERS =================
    // Comentários que usam os dados do post (temporada, lance, transferência, despedida)
    ctx: {
      season: {
        up: ['{stat} e ainda tem gente que critica 😤', '{jogos} jogos e eu vi todos, não perco um 📺', 'Nota {nota}?? Pouco! Merecia 10!', 'Você foi o melhor do time de longe',
          'Fiz uma planilha com os seus números da temporada. Ficou linda 📊', 'Eu sabia desde o primeiro jogo que esse ano ia ser especial', 'Contra tudo e contra todos! Que temporada, {n}!',
          'Quero essa temporada em DVD 📀', 'Coloca esses números no currículo e manda pra Seleção 📄', 'A {num} nunca foi tão bem usada 👕'],
        down: ['Nota {nota}? Eu vi pior, relaxa 😅', '{pos}º lugar não é a sua cara, mas ano que vem a gente sobe', 'O time não ajudou também, né?', 'Você foi o único que correu esse ano, sério',
          'Ano estranho, mas eu sei do que você é capaz', 'Pode ter certeza que a torcida não esqueceu as temporadas boas', 'Respira, descansa e volta. A {num} te espera'],
      },
      moment: {
        up: ["Eu tava no estádio nesse lance aos {min}'!! 😭", 'Contra {vs} é sempre mais gostoso 😏', 'Assisti esse lance 37 vezes já', "Meu vizinho ouviu meu grito aos {min}' kkkk",
          'Eu desliguei a TV de nervoso e liguei de novo bem na hora 😂', 'Esse lance vai passar no replay até 2090', 'Chorei no sofá, no carro e no trabalho no dia seguinte 😭',
          "Aos {min}'! Coração não aguenta, {n}!", 'Pra quem disse que ele não decide jogo grande 🤫', 'O narrador perdeu a voz e eu também 🗣️', 'Melhor lance que eu já vi ao vivo, sério'],
        down: ['Acontece com os melhores, {n}. Cabeça erguida', 'Um lance não apaga tudo que você fez', "Aos {min}' dói, mas a gente tá contigo", 'Foi por um detalhe. Próxima é tua',
          'Até os maiores erraram, irmão', 'Contra {vs} a gente se vinga ano que vem 😤', 'O time inteiro tem culpa, não só você', 'Não dormi também. Mas ainda acredito'],
      },
      transfer: ['Bem-vindo, {n}! Já comprei a camisa {num} 👕', 'Era o reforço que faltava!', 'Diretoria acertou demais nessa!', 'Seja bem-vindo à maior torcida que existe {cor}',
        'Torcida antiga chorando e a nova comemorando 😂', 'Primeiro gol já tá agendado, né?', 'Estreia quando? Já quero ingresso 🎟️', 'Contratação do ano, sem discussão',
        'Vem fazer história, {n}! {cor}', 'Já tô vendo você levantando taça aqui 🏆', 'Nem acredito que você agora joga {noTime}! 😍'],
      bye: ['{temps} temporadas de alegria. Obrigado por cada uma', '{gols} gols e cada um com uma memória pra mim', 'Cresci te vendo jogar. Agora vou envelhecer contando suas histórias 🥹',
        'Vou guardar sua camisa {num} pra sempre', 'Sem você o domingo vai ficar mais chato 😢', 'Faz um jogo de despedida, por favor! 🙏', 'A {num} tinha que ser aposentada junto com você'],
    },
    fans: {
      up: [
        'Nosso camisa {num}! Fica pra sempre {cor}', 'Que fase, {n}! Obrigado por tudo!', 'Melhor jogador que já vi com essa camisa 😍', 'Craque dentro e fora de campo 👏',
        'Renova logo esse contrato, diretoria!! 🙏', 'Já comprei a camisa {num} pro meu filho 😍', 'Meu ídolo!!! Responde aí 🙏🙏', 'Monstro! Monstro! Monstro! 🔥',
        'Te amo, {n}!!! (minha namorada que lute) 😂', 'Esse é o cara! 🐐', 'Tatuei seu rosto na perna, é verdade 😅', 'Se fosse em outro clube, já tava na Seleção!',
        'Melhor contratação da história {doTime} 🙌', 'Chorei no seu gol, sério 😭', 'Você joga o que eu jogo no videogame 🎮', 'Respeita o camisa {num}!!',
        'Quando a bola tá com você, eu já levanto da cadeira 🙌', 'Pai de todos! 👑', 'Obrigado por existir, {n} 🙏', 'Meu avô de 90 anos disse que nunca viu nada igual 👴{cor}',
        'Coloquei seu nome no meu gato. Ele é péssimo de bola, mas tudo bem 🐱', 'Faltei a aula pra te ver jogar. Valeu a pena (mãe, se tiver lendo, é mentira)', 'Craque é pouco!',
        'Esse menino merece estátua na porta do estádio 🗿', 'Toda vez que você pega na bola eu grito "VAI!" e assusto a família', 'Fiz bolo com o seu rosto no meu aniversário 🎂',
        'Minha filha aprendeu a falar "{n}" antes de "papai" 😂', 'Até minha sogra, que odeia futebol, sabe quem é você', 'Gênio! 🧠⚽', 'Para de jogar tanto, tá deixando o resto do time feio 😂',
        'Melhor do mundo e não aceito discussão', 'O dia que você sair daqui eu paro de torcer', 'Ídolo da minha infância e da minha fase adulta também', 'Que fase!! Respeita! 🔥',
        'Comprei ingresso só pra te ver aquecer', 'Pode pedir o que quiser que a torcida dá {cor}', 'Lindo demais ver você jogando', 'Isso aqui é craque de verdade, não é de internet',
        'Você precisa de um prêmio só pra você', 'Me dá sua chuteira de presente de aniversário? 🥺',
      ],
      down: [
        'Ano que vem é nosso, {n}! Confia!', 'Tamo junto nas boas e nas ruins 🙏', 'Volta mais forte, craque!', 'Ainda acredito em você, {n} 💪',
        'Fase ruim todo mundo tem, cabeça erguida!', 'A torcida tá contigo! {cor}', 'Bora reagir, camisa {num}! 🔥', 'Só os fortes sabem levantar 💪',
        'Eu sigo te defendendo no grupo da família 😂🙏', 'Não liga pros haters, {n}!', 'Vai voltar a ser aquele de antes, eu sei!', 'Fé! 🙏',
        'Respira e volta, craque!', 'Meu ídolo continua sendo meu ídolo {cor}', 'Ano difícil pra todo mundo, bora!', 'Os craques também caem. A diferença é que eles levantam',
        'Discuti com meu cunhado por sua causa. Não me deixa na mão ano que vem 😂', 'Treina, descansa e volta voando ✈️', 'Ninguém esquece o que você já fez aqui',
        'Eu acredito mais em você do que no meu time de várzea', 'Um ano ruim não apaga uma história', '{time} precisa de você inteiro. Cuida da cabeça 🙏', 'Força, craque. A gente sabe do que você é capaz',
        'Desliga o celular, vai pra praia e volta com tudo 🏖️', 'Torcida de verdade aparece na hora ruim. Tô aqui {cor}',
      ],
      bye: [
        'Não vai não 😭😭', 'Obrigado por tudo, {n}! Eterno ídolo {cor}', 'Chorei aqui 😭 Que carreira!', 'Vou contar pros meus filhos que vi o {n} jogar 🥹',
        'Volta, nem que seja pro jogo de despedida! 😭', 'Sem você o futebol fica mais chato 😢', 'Obrigado pelas alegrias! 🙏', 'Lenda! Lenda! Lenda! 🐐',
        'Meu filho tem seu nome. Sério 🥹', 'Pode virar técnico {doTime} agora? 👀', 'Hoje é dia de chorar no banho 😭', 'Um pedaço da minha infância se aposenta hoje 🥺',
        'Ainda dá tempo de mudar de ideia, viu?', 'Minha mãe chorou mais que eu, e ela nem gosta de futebol', 'Que honra ter vivido a sua época', 'Vou emoldurar o ingresso do seu último jogo 🖼️',
        'O futebol te agradece. E eu também', 'Agora vai ter tempo pra responder os fãs, né? 👀', 'Fim de uma era 😢', 'Aposenta o jogador, mas não aposenta o ídolo {cor}',
      ],
    },
    // Comentários aleatórios que aparecem em qualquer post (a internet sendo a internet)
    random: [
      'Primeiro! 🥇', 'Alguém em 2077 vendo isso?', 'Sorteio? 👀', 'Me segue de volta 🙏', 'Quem veio pelo TikTok? 🙋', 'Mãe, eu tô na internet!',
      'Joga no meu time de várzea sábado? Pago o churrasco 🍖', 'Ainda tenho sua figurinha brilhante 🥹', 'Comentei antes do Neto!', 'Ganha 5 mil por dia? Clica no link 😂',
      'Só vim ver os comentários', 'Responde que eu mostro pra minha sala inteira 🙏', 'Ele leu meu comentário, eu sei', 'Esse post merecia 1 milhão de curtidas',
      'Já é o terceiro post que eu comento hoje, me nota 🙏', 'Nem li, mas concordo', 'Fui marcado aqui por engano?', 'Cadê o Casimiro comentando?? 😂',
      'Vende essa chuteira pra mim?', 'Seu cabelo tá diferente, gostei', 'Parabéns pelo aniversário! (não é hoje? ah, desculpa)', 'Meu pai disse que joga mais que você 😂',
      'A legenda tá linda, foi o assessor que escreveu? 😂', 'Mano, tava no estádio e chorei', 'Quando vai lançar a biografia?', 'Ativa as notificações, rapaziada 🔔',
      'Não gostei... asmei! 😂', 'Alguém sabe a senha do wi-fi do estádio?', 'Vim pelo meme, fiquei pelo craque', 'Faz uma dancinha nova na próxima comemoração 💃',
      'Qual é o shampoo? Pergunta séria', 'Me adota? Eu lavo a louça 🍽️', 'Tô no trabalho fingindo que tô trabalhando e vendo seus posts', 'Hoje é sexta? Perdi a noção do tempo',
      'Quem é você? (brincadeira, te amo)', 'Desce o link da camisa', 'Meu horóscopo disse que hoje você ia postar. Acertou ✨', 'Comenta "eu" se você também ama esse cara',
      'Se esse comentário tiver 100 curtidas eu raspo a cabeça', 'Vim aqui só pra dizer que meu time é melhor (mentira, vim te elogiar)', 'Alguém viu meu cachorro? É caramelo 🐕',
      'Tô esperando o post da comemoração desde ontem', 'O fotógrafo merece aumento', 'Segue a página do meu tio, ele vende açaí 🍧', 'Chama no direct, tenho uma proposta de time de várzea',
      'POV: você abriu o Instagram só pra ver isso', 'Esse post tá dando mais engajamento que reality show', 'Meu professor de educação física disse que te treinou. Será?',
      'Eu e meus 3 seguidores te apoiamos', 'Qual o segredo? Comer brócolis?', 'Alguém traduz pra minha avó que ele é craque?', 'Vovó mandou um beijo 👵',
      'Já mostrei esse post pro meu chefe pra justificar a falta de ontem', 'Imagina jogar contra esse cara. Medo', 'Vou fazer meu TCC sobre você', 'Pior que eu ia comentar a mesma coisa',
      'Só sei que nada sei, mas sei que você é craque', 'Grupo da família já tá discutindo esse post', 'Deixa eu ser seu reserva? Pelo menos no pôquer', 'Me empresta 10 reais? 😂',
    ],
    // Páginas de notícia e de memes (verificadas, sem o nome de nenhuma página real)
    pages: [
      ['central.da.bola', '🚨 {n} posta mensagem e a web reage'], ['bastidores.fc', 'URGENTE: {n} acaba de postar. Fontes indicam que ele está feliz 😂'], ['memes.da.bola', 'Quando o {n} posta: "obrigado, Deus". Quando eu posto: "boa noite, grupo" 😂'],
      ['futebol.em.dados', '📊 {n} é o assunto mais comentado do dia no futebol'], ['mercado.da.bola', '👀 Clubes de fora acompanham o momento do {n}'], ['resenha.esportiva', 'O post do {n} já passou de mil comentários em 10 minutos 🔥'],
      ['torcedor.noticias', 'Torcida reage ao post do {n}: "ídolo"'], ['bola.de.cristal', 'Previsão: o {n} vai postar de novo na semana que vem 🔮'], ['jogadas.raras', 'Lembram daquele lance do {n}? Pois é. Ele postou hoje 👇'],
      ['quadro.tatico', 'Análise: o que o post do {n} diz sobre o próximo ano 🧐'],
    ],
    haters: {
      up: [
        'Ainda acho superestimado 🤷', 'Contra time grande quero ver...', 'Esse post tá mais bonito que a temporada kkkk', 'Sorte de principiante 🙄', 'No videogame eu faço melhor 🎮',
        'Assessoria trabalhando bem hein', 'Meu sobrinho de 8 anos faria igual', 'Quero ver repetir ano que vem 🤨', 'Jogou bem, tá. Mas aquele pênalti de 2 anos atrás eu não esqueci 😤',
        'Mais marketing que futebol 🤷', 'Contra time pequeno é fácil', 'Bom jogador, péssimo gosto pra roupa', 'Quando jogar no meu time eu elogio', 'Hype demais pra pouco jogador',
        'Juiz ajudou em metade desses jogos aí', 'Tá bom, tá bom, mas e a Copa?', 'Esse aí só aparece em foto 📸', 'Ano que vem volta pro normal, anota',
        'Meu time tem três iguais a ele no banco', 'Joga bem, mas comemora feio', 'Esperando o dia que ele erra pra eu voltar aqui 👀', 'Se fosse eu com esse salário, fazia o dobro',
        'Parabéns, mas eu continuo preferindo o reserva', 'Superestimado, nota 5', 'Ok, mas quantos gols de cabeça?',
      ],
      down: [
        'Tá na hora de pendurar a chuteira 😴', 'Salário alto pra pouca coisa...', 'Volta pro banco 🙄', 'Postando em vez de treinar?', 'Devolve o dinheiro do meu ingresso 😤',
        'Esse aí só joga no Instagram', 'Se fosse eu, já tinha ido embora', 'Corre mais que reclama, pelo menos? 🤨', 'Meu cachorro corre mais em campo 🐕', 'Cadê o craque? Só vejo o influencer',
        'Vende pro rival, por favor 🙏', 'Pelo menos o cabelo tá bonito', 'Ano todo assim e ainda posta foto?', 'Desliga o celular e vai treinar', 'Já foi bom um dia. Um dia.',
        'Contratação mais cara e mais inútil', 'Se ele jogar ano que vem eu cancelo o sócio', 'Meu avô de bengala marca mais', 'Postou rápido, joga devagar', 'Esse ano ele jogou de pantufa',
        'Vou pedir reembolso da camisa {num}', 'Pior que o técnico ainda escala', 'Desaprendeu a jogar?', 'Fase ruim ou jogador ruim?', 'Tão bonzinho quem diz que foi só uma fase',
      ],
      bye: ['Já foi tarde 🙄 (brincadeira, valeu, craque)', 'Finalmente vai dar espaço pros novos', 'Vai fazer falta... pros adversários 😂', 'Aposentou tarde, mas aposentou',
        'Vou sentir falta de reclamar de você 😢', 'Mesmo eu, que sempre critiquei: obrigado', 'Agora vai jogar só no showbol?', 'Pena que eu torci contra a carreira toda e não adiantou 😂'],
    },
    // O jogador às vezes responde o hater
    replies: [
      'Te espero na próxima, parça 😘', 'Anotado. Obrigado pela motivação 🙏', 'Kkkkk depois a gente conversa no gramado', 'Tá bom, professor 😂', 'Vou mostrar pra minha mãe, ela vai adorar 😂',
      'Bom dia pra você também ☀️', 'Valeu pela audiência 📈', 'Salvei seu comentário pra ler depois do próximo título 📌', 'Seu cachorro tá convidado pro treino 🐕', 'Com esse ânimo, quer ser meu preparador físico?',
      'Tô treinando, só parei pra te responder 😂', 'Uma hora você vira fã. Eu espero ⏳', 'Opinião anotada no meu caderno de motivação 📒', 'Obrigado pelo engajamento, ajuda muito 🙏', 'Relaxa, ano que vem eu te dou motivo pra apagar isso',
      'Kkkkkkkk essa foi boa, admito', 'Se quiser, te mando um ingresso pra ver de perto', 'Meu avô também achava isso. Hoje é meu fã 😂', 'Vou dedicar o próximo gol pra você 😘', 'Paz e amor, irmão ✌️',
      'Respeito sua opinião. E discordo dela 😂', 'Te vejo no próximo post 👋', 'Esse comentário vai pro mural do vestiário 😂', 'Fica tranquilo, eu também me cobro', 'Toma uma água, tá calor 💧',
    ],
    club: {
      up: ['Orgulho de ter você com a nossa camisa! 💪', 'Que temporada, {n}! 👏', 'Esse é o nosso camisa {num}! 🔥', 'Ídolo! 👑', '{time} agradece, craque! 🙌',
        'Vem renovar logo que o presidente tá ansioso 😂✍️', 'Camisa {num} esgotada na loja oficial. Coincidência? 👕', 'A casa é sua, {n}! 🏟️', 'Craque é craque {cor}', 'Nosso orgulho! {cor}',
        'O CT inteiro tá comentando esse post 😂', 'Que venha mais! 🚀', 'Obrigado por honrar essa camisa 🙏', 'O roupeiro já separou a camisa do próximo jogo 👕'],
      down: ['Seguimos juntos, {n}. 🤝', 'Força, camisa {num}! Estamos contigo 💪', 'Família {time} unida! 🙌', 'O clube confia em você 🤝', 'Juntos, a gente vira essa página 💪',
        'Ano que vem é nosso, {n} {cor}', 'Cabeça erguida. {time} está com você 🙏', 'Treino amanhã às 9h. Bora! ⏰😉'],
      bye: ['Obrigado por tudo, {n}. Sua história está escrita aqui. 🙌', 'Eterno camisa {num}. Obrigado! 👑', 'A camisa {num} vai ficar guardada com carinho 🙏', 'Seu lugar no museu do clube já está reservado 🏛️',
        'Uma lenda nunca sai de verdade. Obrigado, {n} {cor}', 'As portas {doTime} vão estar sempre abertas 🚪', 'Obrigado pelos gols, pelas taças e pela entrega 🙏', 'Hoje o clube inteiro te aplaude de pé 👏'],
    },
    // Sufixos neutros (nada de apelido de torcida, que é de um clube só)
    fanHandles: ['_raiz', 'dacadeira', '_doente', '.apaixonado', '_desde1999', 'naveia', '_resenha', '.torcedor', '_arquibancada', 'nocoracao', '_sempre', 'roxo', '_ate.morrer', '.socio', '_doestadio', 'dofundao'],
    randomHandles: ['arquibancada_89', 'torcedor_raiz', 'resenha.fc', 'futebolraiz', 'joaozinho_2012', 'tia.do.zap', 'memes.da.bola', 'varzea_fc', 'vovo_boleiro', 'zueira_fc', 'goleiro.de.fifa',
      'pai_do_craque', 'menino.da.vila', 'sofascore_humano', 'mestre.da.prancheta', 'camisa10.de.varzea', 'tio.do.churrasco', 'dona.cida.futebol', 'lateral.ofensivo', 'reserva.do.reserva',
      'fa.numero.1', 'peladeiro.de.quinta', 'narrador.de.sofa', 'figurinhas.repetidas', 'coach.da.bola', 'gandula_oficial', 'bola.murcha', 'chuteira.velha', 'cabeca.de.area', 'canela.fina'],
    haterHandles: ['opiniao_sincera', 'futebol.critico', 'secador_oficial', 'tecnico_de_sofa', 'sincerao_fc', 'anti.modinha', 'xerife.das.redes', 'corneteiro.oficial', 'nunca.satisfeito', 'zica.fc', 'do.contra_'],
  };
})();
