// Nas redes: textos dos posts do jogador e dos comentários (torcida, haters, clube e famosos).
// Tudo fictício, para a simulação. Marcadores: {n} nome, {time} clube, {num} número da camisa, {idade} idade,
// {cor} coração na cor do clube, {stat} estatística da temporada (gols, assistências, desarmes ou jogos sem sofrer gol), {temps} temporadas,
// {gols} gols na carreira, {assist} assistências na carreira, {titulos} títulos do ano.
(function () {
  const D = window.CRAQUE_DATA;
  D.SOCIAL = {
    // ---------- posts do jogador ----------
    posts: {
      ballon: [
        'Bola de Ouro. Nem nos meus sonhos de moleque eu imaginei isso. Obrigado a todos que estiveram comigo! 🏆✨',
        'O moleque que jogava descalço na rua agora é o melhor do mundo. Mãe, a gente conseguiu! 🏆😭',
        'Melhor do mundo. Escrevi isso num caderno aos 10 anos. Hoje eu fecho esse caderno. 🏆',
        'Dedico essa Bola de Ouro a cada pessoa que disse que eu não ia chegar. Obrigado pela motivação 😂🏆',
        'Sem palavras. Só gratidão. E um espaço novo na estante de casa 🏆✨',
        'Bola de Ouro! Agora preciso aprender a fazer discurso em inglês 😅🏆',
      ],
      title: [
        'CAMPEÕES! 🏆 {titulos}. Temporada de muito trabalho. Obrigado, {time}!',
        'É campeão! 🏆 {stat} e uma taça pra guardar pra sempre. Obrigado, torcida!',
        'Pode soltar o grito que tá preso na garganta: É CAMPEÃO! 🏆🔥',
        'Taça na mão, sorriso no rosto e zero voz depois da festa 🏆🗣️',
        'Quem duvidou, segura essa! {titulos} é nosso! 🏆',
        'Mais uma pra galeria. E a de vocês, torcida, é a mais bonita {cor}🏆',
        'Dormi abraçado com a taça. Não me julguem 🏆😴',
        'Campeão! Agora a resenha vai até segunda-feira 🍖🏆',
      ],
      great: [
        '{stat}. Temporada pra guardar na memória. Obrigado, {time}! 💪',
        'Que ano! {stat} e muito orgulho dessa camisa. Bora pra mais! 🔥',
        '{stat}. Trabalho em silêncio, resultado no gramado. 🤫⚽',
        'Fechando a temporada com {stat}. O segredo? Arroz, feijão e muito treino 🍚💪',
        'Eu só queria agradecer a Deus, à família e ao fisioterapeuta, que não teve folga nenhuma esse ano 😂🙏',
        'Temporada dos sonhos. {stat}. Ano que vem tem mais! 🚀',
        'Os números falam: {stat}. Eu só falo obrigado 🙏',
      ],
      good: [
        '{stat}, uma temporada de entrega e muito orgulho de vestir essa camisa. Obrigado, {time}! 💪',
        'Temporada de evolução. {stat} e a certeza de que dá pra mais. 💪',
        'Nem tudo foi perfeito, mas teve muita entrega. {stat}. Seguimos! 🙌',
        'Fecho o ano com {stat} e a cabeça no próximo. Férias? Só uma semaninha 😅',
        'Ano bom, mas eu sou chato comigo mesmo: quero mais. Bora! 🔥',
        'Obrigado, {time}! Cada jogo com essa camisa vale a pena 💪',
      ],
      bad: [
        'Não foi a temporada que eu queria. Vou trabalhar em dobro pra voltar mais forte. 🙏',
        'Ano abaixo do que eu espero de mim. Cabeça no lugar e trabalho. 💪',
        'Tem ano que a bola não entra. Esse foi um deles. O próximo vai ser diferente. 🙏',
        'Li todas as críticas. Algumas foram justas. Outras foram da minha tia 😅 Bora reagir!',
        'Peço desculpas pelo ano. Prometo voltar com fome. 🍽️⚽',
        'Fase ruim? Sim. Fim da linha? Nem de longe. 💪',
      ],
      bench: [
        'Poucos minutos esse ano, mas sigo trabalhando todo dia. Minha hora vai chegar. 💪',
        'Banco é lugar de descanso. Eu prefiro o gramado. Seguimos treinando! 🔥',
        'Conheci cada detalhe do banco de reservas esse ano. Agora quero conhecer o gramado de novo 😅',
        'Paciência e treino. Quando a chance vier, eu tô pronto. 🙏',
        'Ano de muito aprendizado vendo de fora. Ano que vem é de dentro. 💪',
      ],
      injury: [
        'Ano difícil, longe dos gramados. Obrigado pelo carinho de todos. Já já tô de volta! 🙏',
        'Fisioterapia, gelo e muita paciência. Volto mais forte, prometo. 💪',
        'O corpo pediu uma pausa. A cabeça já tá no próximo jogo. 🙏',
        'Obrigado aos médicos e fisioterapeutas. Vocês viram mais de mim esse ano do que a minha família 😂',
        'Lesão não escolhe hora. Mas eu escolho como voltar: melhor. 💪',
      ],
      down: [
        'Dói demais. Peço desculpas à torcida. A gente vai voltar. 💔',
        'Rebaixamento é a pior sensação do futebol. Assumo a minha parte. 💔',
        'Hoje não tem frase bonita. Só tristeza e a promessa de reconstruir. 🙏',
        'Desculpa, torcida. Vocês mereciam mais. 💔',
      ],
      eventOk: [
        'Decisão tomada, foco total no que importa: o campo. 💪',
        'Mais um capítulo da história. Seguimos! 🙌',
        'Dia importante hoje. Gratidão por tudo! 🙏',
        'Tudo certo por aqui. Agora é bola pra frente ⚽',
        'Boas notícias pra quem torce por mim 😉',
        'Quem me conhece sabe: eu escolho com o coração e com a cabeça. 💪',
        'Fase boa dentro e fora de campo. Obrigado, Deus! 🙏',
      ],
      eventKo: [
        'Nem tudo sai como a gente planeja. Cabeça erguida e bola pra frente. 🙏',
        'Dia difícil. Aprendizado e sigo em frente. 💪',
        'Errar faz parte. Insistir no erro, não. Bora! 🔥',
        'Semana complicada. Obrigado a quem mandou mensagem de apoio 🙏',
        'Respira, treina e segue. 💪',
      ],
      transfer: [
        'Novo capítulo! Muito feliz de chegar {aoTime}. Vamos com tudo! ✍️',
        'Assinado! ✍️ Obrigado pela confiança, {time}. Bora fazer história!',
        'Mala pronta, chuteira na mochila e muita vontade. Cheguei, {time}! 🧳⚽',
        'Novo clube, mesmo sonho. Vamos juntos, {time}! 💪',
        'Já decorei o hino. Agora é jogar 😄 Obrigado, {time}!',
      ],
      momentOk: {
        goal: ['Que gol!', 'Bati e saí pro abraço!', 'Coração na boca e bola na rede!', 'Eu sabia que ia entrar!', 'Nem olhei pro goleiro, só bati!'],
        save: ['Que defesa!', 'Fui buscar lá no canto!', 'Hoje não passou nada!', 'Li o batedor e fui!'],
        tackle: ['Bola roubada no último minuto!', 'Carrinho limpo e jogo salvo!', 'Hoje não passou ninguém!', 'Cheguei na hora certa!'],
        pass: ['Que passe!', 'Enfiei e ele só empurrou!', 'Vi a brecha e coloquei na medida!', 'Assistência com açúcar!'],
      },
      momentEnd: {
        cup: ['É CAMPEÃO! 🏆', 'A taça é nossa! 🏆'], cont: ['É CAMPEÃO! 🏆', 'Campeões do continente! 🏆🌎'],
        title: ['O título é nosso! 🏆', 'Campeão da liga! 🏆'], acesso: ['ACESSO! 🚀', 'Subimos! 🚀'],
        classico: ['Clássico é clássico, e é nosso! 🔥', 'Clássico com a nossa cara! 🔥'],
      },
      momentTail: ['Isso aqui é pra vocês, torcida!', 'Dedico à minha família!', 'Que noite inesquecível!', 'Ninguém dorme hoje!', 'Arrepiado até agora!'],
      momentKo: [
        'Assumo a responsabilidade. Dói, mas vou voltar mais forte. 🙏',
        'Não foi dessa vez. Obrigado pelo apoio de sempre, torcida. 💔',
        'Eu queria muito dar essa alegria pra vocês. Desculpa. 💔',
        'Futebol às vezes é cruel. Mas eu volto. 🙏',
        'Vou rever esse lance mil vezes. E na próxima, vai. 💪',
      ],
      announce: [
        'Chegou a hora. Essa vai ser minha última temporada como jogador. Quero aproveitar cada jogo ao lado de vocês. Obrigado, futebol! ⚽🙏',
        'Última temporada. Vou jogar cada partida como se fosse a primeira. Obrigado por tudo! 🙏',
        'Decidi: essa é a última dança. Bora fazer ela valer! 💃⚽',
        'Os joelhos mandaram um recado e eu resolvi ouvir 😅 Última temporada, vamos com tudo!',
      ],
      farewell: [
        'Hoje eu me despeço dos gramados. {temps} temporadas, {gols} gols, {assist} assistências. Obrigado, futebol. ⚽❤️',
        'Fim. {temps} temporadas e uma vida inteira de gratidão. Obrigado a cada torcedor. 🙏',
        'Pendurei as chuteiras. Literalmente: tão na parede da sala agora 😂 Obrigado por tudo!',
        'O menino que sonhava virou jogador. O jogador agora vira torcedor. Obrigado, futebol! ⚽❤️',
        '{gols} gols, {assist} assistências e milhões de abraços. Hoje eu paro. Obrigado! 🙏',
      ],
    },

    // ---------- famosos (fama mínima para comentar e falas no estilo de cada um) ----------
    famous: [
      { h: 'craqueneto', min: 30,
        up: ['Joga muito! Eu falei, meu, eu falei!', 'Isso aqui é jogador! Respeita o {n}!', 'Ô, meu, que fase! Tem que estar na Seleção!', 'Eu tô falando há anos desse menino! Anos!', 'Se não convocar o {n}, eu paro de assistir à Seleção!', 'Gente, isso é craque! Não é qualquer um, não!'],
        down: ['Acorda, {n}! Você pode muito mais, meu!', 'Eu cobro porque acredito. Bora reagir!', 'Pelo amor de Deus, {n}, que ano foi esse?', 'Não dá, meu! Não dá! Tem que melhorar!'],
        bye: ['Obrigado por tudo, {n}! O futebol vai sentir falta, meu!', 'Que carreira, meu! Vem comentar jogo comigo agora!'] },
      { h: 'casimiro', min: 30,
        up: ['Ih, meteu essa? 😂🔥', 'Muito forte, mané!', 'Simplesmente amassa.', 'Tu tá de sacanagem comigo? Que fase! 😂', 'Aceitas pix? Quero pagar o ingresso desse show 😂', 'Qual é, tranquilão? 😎', 'Apenas o {n} sendo o {n}.'],
        down: ['Que papinho, hein? 😂 Bora, reage!', 'Ih, mané... 😅 Ano que vem é outro papo', 'Tu tá de sacanagem comigo? Volta a jogar, mané!'],
        bye: ['Lenda. Simplesmente. Apenas. 🙏', 'Ih, meteu essa? Vai parar? Aceitas convite pra live? 📺'] },
      { h: 'podpah', min: 30,
        up: ['Brabo demais, mano! Vem pro Podpah contar essa 🎙️', 'É o pai! 🔥🔥', 'Papo reto: o {n} tá voando, mano!', 'Cê é loko, mano! Que fase!', 'Mano do céu! Monstro! 🔥'],
        down: ['Força, mano! Vem pro Podpah desabafar kkkk 🎙️', 'Cabeça erguida, mano, ano que vem é teu!', 'Pô, mano, acontece! Tamo junto!'],
        bye: ['Lenda, mano! A cadeira do Podpah te espera 🎙️', 'É o pai pra sempre, mano! 🙌'] },
      { h: 'flowsportclub', min: 30,
        up: ['Aí é cinema! 🎬', 'Olha o nível, rapaziada!', 'Isso é absurdo, rapaziada! 🔥', 'A resenha de hoje já tem pauta 😂🎙️'],
        down: ['Fase ruim passa, rapaziada. Confia!', 'A resenha tá contigo, {n}!'],
        bye: ['Resenha marcada pra contar essa história toda! 🎙️'] },
      { h: 'luvadepedreiro', min: 30,
        up: ['RECEBA! 🙏⚽', 'Obrigado, meu Deus! Que fase do {n}! RECEBA!', 'Receeeeba! O {n} é monstro! 🙏'],
        down: ['Confia em Deus que vai dar certo, irmão! 🙏', 'Receba a força, {n}! 🙏'],
        bye: ['Obrigado, meu Deus, por essa carreira! RECEBA! 🙏'] },
      { h: 'galvaobueno', min: 80,
        up: ['Haja coração, amigo! ❤️', 'Bem, amigos... que temporada do {n}!', 'É do Brasil! É do {n}!', 'Pode isso, Arnaldo? Pode! 😂'],
        down: ['Calma, amigo. O futebol dá voltas.', 'Bem, amigos... nem sempre se ganha.'],
        bye: ['Bem, amigos... uma carreira para a história. Obrigado, {n}! 🙏'] },
      { h: 'kaka', min: 80,
        up: ['Que temporada! Segue firme e humilde 🙏👏', 'Visão de jogo não tem idade. Parabéns! 👏', 'Muito feliz pelo seu momento! Deus abençoe 🙏', 'Jogo bonito e elegante. Parabéns! 👏'],
        down: ['Momentos difíceis fazem parte. Confio muito em você 🙏', 'Cabeça no lugar. Você vai voltar 🙏'],
        bye: ['Uma carreira linda. Obrigado pelo futebol 🙏', 'Parabéns por tudo! Foi uma honra ver você jogar 👏'] },
      { h: 'ronaldinho', min: 80,
        up: ['Alegria demais te ver jogar, irmão! 😁⚽', 'Joga bonito sempre! 🤙', 'Que magia, irmão! 😁🤙', 'Isso é futebol arte! 🤙⚽'],
        down: ['Sorri, irmão! Futebol é alegria 😁🤙', 'Relaxa e se diverte, irmão 🤙'],
        bye: ['Obrigado pelas jogadas, irmão! Agora é só alegria 😁🤙'] },
      { h: 'romario', min: 80,
        up: ['Craque é craque. Tá no caminho certo 👊', 'Gostei. Muito bom.', 'Lembra eu. Mas eu era melhor 😎', 'Fez o básico bem feito. Gol é isso.'],
        down: ['Tem que decidir mais. Simples assim.', 'Treina finalização. Depois a gente conversa.'],
        bye: ['Grande jogador. Bem-vindo ao clube dos aposentados 😎'] },
      { h: 'reymarjr', min: 150,
        up: ['Monstro demais, parceiro! 👏🔥', 'Tamo junto, mlk! Que fase! 🔥', 'Ousadia e alegria, parceiro! 🤙', 'Brabo! Vem jogar comigo no pôquer 😂🃏'],
        down: ['Cabeça erguida, parceiro. Volta mais forte! 🙏', 'Já passei por isso, mlk. Vai dar certo! 💪'],
        bye: ['Gigante! Obrigado por tudo, parceiro. Lenda! 🐐'] },
      { h: 'vinijr', min: 150,
        up: ['Baila, {n}! 💃🔥', 'Que temporada, irmão! Bora! 🔥', 'Ninguém para, irmão! 🚀', 'Dança comigo na comemoração da próxima! 💃'],
        down: ['Segue firme, irmão. Ninguém para a gente 💪', 'Vai passar, irmão. Tamo junto 🙏'],
        bye: ['Inspiração pra todos nós. Obrigado, lenda! 🙌'] },
      { h: 'r9fenomeno', min: 150,
        up: ['Fenômeno reconhece fenômeno 😄👏', 'Que fase! Aproveita cada momento 👏', 'Faz gol que nem eu: com o sorriso 😁'],
        down: ['Lesão e fase ruim eu conheço bem. Você volta! 💪'],
        bye: ['Que carreira! Parabéns, {n} 👏'] },
    ],

    // ---------- torcida ----------
    fans: {
      up: [
        'Nosso camisa {num}! Fica pra sempre {cor}', 'Que fase, {n}! Obrigado por tudo!', 'Melhor jogador que já vi com essa camisa 😍', 'Craque dentro e fora de campo 👏',
        'Renova logo esse contrato, diretoria!! 🙏', 'Já comprei a camisa {num} pro meu filho 😍', 'Meu ídolo!!! Responde aí 🙏🙏', 'Monstro! Monstro! Monstro! 🔥',
        'Te amo, {n}!!! (minha namorada que lute) 😂', 'Esse é o cara! 🐐', 'Tatuei seu rosto na perna, é verdade 😅', 'Se fosse em outro clube, já tava na Seleção!',
        'Melhor contratação da história do {time} 🙌', 'Chorei no gol de você, sério 😭', 'Você joga o que eu jogo no videogame 🎮', 'Respeita o camisa {num}!!',
        'Quando a bola tá com você, eu já levanto da cadeira 🙌', 'Pai de todos! 👑', 'Obrigado por existir, {n} 🙏', 'Meu avô de 90 anos disse que nunca viu nada igual 👴❤️',
      ],
      down: [
        'Ano que vem é nosso, {n}! Confia!', 'Tamo junto nas boas e nas ruins 🙏', 'Volta mais forte, craque!', 'Ainda acredito em você, {n} 💪',
        'Fase ruim todo mundo tem, cabeça erguida!', 'A torcida tá contigo! {cor}', 'Bora reagir, camisa {num}! 🔥', 'Só os fortes sabem levantar 💪',
        'Eu sigo te defendendo no grupo da família 😂🙏', 'Não liga pros haters, {n}!', 'Vai voltar a ser aquele de antes, eu sei!', 'Fé! 🙏',
        'Respira e volta, craque!', 'Meu ídolo continua sendo meu ídolo {cor}', 'Ano difícil pra todo mundo, bora!',
      ],
      bye: [
        'Não vai não 😭😭', 'Obrigado por tudo, {n}! Eterno ídolo {cor}', 'Chorei aqui 😭 Que carreira!', 'Vou contar pros meus filhos que vi o {n} jogar 🥹',
        'Volta, nem que seja pro jogo de despedida! 😭', 'Sem você o futebol fica mais chato 😢', 'Obrigado pelas alegrias! 🙏', 'Lenda! Lenda! Lenda! 🐐',
        'Meu filho tem seu nome. Sério 🥹', 'Pode virar técnico do {time} agora? 👀', 'Hoje é dia de chorar no banho 😭', 'Um pedaço da minha infância se aposenta hoje 🥺',
      ],
    },
    // Comentários aleatórios que aparecem em qualquer post (a internet sendo a internet)
    random: [
      'Primeiro! 🥇', 'Alguém em 2077 vendo isso?', 'Sorteio? 👀', 'Me segue de volta 🙏', 'Quem veio pelo TikTok? 🙋', 'Mãe, eu tô na internet!',
      'Joga no meu time de várzea sábado? Pago o churrasco 🍖', 'Ainda tenho sua figurinha brilhante 🥹', 'Comentei antes do Neto!', 'Ganha 5 mil por dia? Clica no link 😂',
      'Só vim ver os comentários', 'Responde que eu mostro pra minha sala inteira 🙏', 'Ele leu meu comentário, eu sei', 'Esse post merecia 1 milhão de curtidas',
      'Já é o terceiro post que eu comento hoje, me nota 🙏', 'Nem li, mas concordo', 'Fui marcado aqui por engano?', 'Cadê o casimiro comentando?? 😂',
      'Vende essa chuteira pra mim?', 'Seu cabelo tá diferente, gostei', 'Parabéns pelo aniversário! (não é hoje? ah, desculpa)', 'Meu pai disse que joga mais que você 😂',
      'A legenda tá linda, foi o assessor que escreveu? 😂', 'Mano, tava no estádio e chorei', 'Quando vai lançar a biografia?', 'Ativa as notificações, rapaziada 🔔',
    ],
    haters: {
      up: [
        'Ainda acho superestimado 🤷', 'Contra time grande quero ver...', 'Esse post tá mais bonito que a temporada kkkk', 'Sorte de principiante 🙄',
        'No videogame eu faço melhor 🎮', 'Assessoria trabalhando bem hein', 'Meu sobrinho de 8 anos faria igual', 'Quero ver repetir ano que vem 🤨',
        'Jogou bem, tá. Mas aquele pênalti de 2 anos atrás eu não esqueci 😤', 'Mais marketing que futebol 🤷',
      ],
      down: [
        'Tá na hora de pendurar a chuteira 😴', 'Salário alto pra pouca coisa...', 'Volta pro banco 🙄', 'Postando em vez de treinar?',
        'Devolve o dinheiro do meu ingresso 😤', 'Esse aí só joga no Instagram', 'Se fosse eu, já tinha ido embora', 'Corre mais que reclama, pelo menos? 🤨',
        'Meu cachorro corre mais em campo 🐕', 'Cadê o craque? Só vejo o influencer', 'Vende pro rival, por favor 🙏', 'Pelo menos o cabelo tá bonito',
      ],
      bye: ['Já foi tarde 🙄 (brincadeira, valeu, craque)', 'Finalmente vai dar espaço pros novos', 'Vai fazer falta... pros adversários 😂'],
    },
    // O jogador às vezes responde o hater
    replies: ['Te espero na próxima, parça 😘', 'Anotado. Obrigado pela motivação 🙏', 'Kkkkk depois a gente conversa no gramado', 'Tá bom, professor 😂', 'Vou mostrar pra minha mãe, ela vai adorar 😂', 'Bom dia pra você também ☀️', 'Valeu pela audiência 📈'],
    club: {
      up: ['Orgulho de ter você com a nossa camisa! 💪', 'Que temporada, {n}! 👏', 'Esse é o nosso camisa {num}! 🔥', 'Ídolo! 👑', 'O {time} agradece, craque! 🙌', 'Vem renovar logo que o presidente tá ansioso 😂✍️'],
      down: ['Seguimos juntos, {n}. 🤝', 'Força, camisa {num}! Estamos contigo 💪', 'Família {time} unida! 🙌'],
      bye: ['Obrigado por tudo, {n}. Sua história está escrita aqui. 🙌', 'Eterno camisa {num}. Obrigado! 👑', 'A camisa {num} vai ficar guardada com carinho 🙏'],
    },
    // Sufixos neutros (nada de apelido de torcida, que é de um clube só)
    fanHandles: ['_raiz', 'dacadeira', '_doente', '.apaixonado', '_desde1999', 'naveia', '_resenha', '.torcedor', '_arquibancada', 'nocoracao', '_sempre', 'roxo'],
    randomHandles: ['arquibancada_89', 'torcedor_raiz', 'resenha.fc', 'futebolraiz', 'joaozinho_2012', 'tia.do.zap', 'memes.da.bola', 'varzea_fc', 'vovo_boleiro', 'zueira_fc', 'goleiro.de.fifa', 'pai_do_craque', 'menino.da.vila', 'sofascore_humano', 'mestre.da.prancheta'],
    haterHandles: ['opiniao_sincera', 'futebol.critico', 'secador_oficial', 'tecnico_de_sofa', 'sincerao_fc', 'anti.modinha', 'xerife.das.redes'],
  };
})();
